#!/usr/bin/env bash
# Pre-create the warehouse relations a fresh cluster must answer for before dbt
# has run, by applying the committed DDL snapshot in scripts/connectors-ddl/.
#
# Bronze is NOT here. It has exactly one creator — the Airbyte
# destination-clickhouse, handed a catalogue built from the connector's own
# `discover` — and a relation pre-created here would win, because every
# statement below is `CREATE ... IF NOT EXISTS`: the destination would then find
# its table already present and leave whatever shape this script gave it.
#
# What remains is the four relations groups a deployment gets from dbt:
# identity, staging, silver and insight. The snapshot is generated by running
# the full bootstrap-db pipeline — real connector `discover`, the real
# destination-clickhouse connector, real dbt models — against a throwaway
# ClickHouse and dumping SHOW CREATE for what it produced
# (scripts/bootstrap-db/dump-ddl.sh), then committing the result.
# .github/workflows/connectors-ddl.yml re-runs that pipeline on every PR and
# fails on any drift; it validates, it never commits.
#
# Apply order is the dependency order: identity and staging first (gold reads
# identity_inputs and the identity_persons mirror through resolve_person_id),
# then silver, then insight, whose views read silver. Statements are separated
# by blank lines in the dump format; views may reference other views, so failed
# statements are retried in additional passes until a pass makes no progress
# (dependency order resolves itself), and only a stuck pass is fatal.
#
# Everything is CREATE ... IF NOT EXISTS / CREATE OR REPLACE VIEW — existing
# relations are never dropped or altered, so re-runs and upgrades are no-ops
# for anything dbt already owns.
#
# Required env (same contract as apply-ch-migrations.sh, via lib/ch-exec.sh):
#   CLICKHOUSE_URL, CLICKHOUSE_USER, CLICKHOUSE_PASSWORD
#
# Generation mode: when this script runs as part of bootstrap-db's snapshot
# REGENERATION (dump-ddl workflow), the connectors-ddl/*.sql on disk are the
# PREVIOUS (stale) snapshot — applying them would leak dropped relations into
# the fresh dump and break convergence. bootstrap-db.sh therefore sets
# BOOTSTRAP_SKIP_SNAPSHOT=1 so this applicator is a no-op during generation;
# the real silver/gold are built from dbt and migrations instead. It stays
# fully active on real deploys (fresh-cluster apply).
set -euo pipefail

if [[ "${BOOTSTRAP_SKIP_SNAPSHOT:-}" == "1" ]]; then
  echo "=== Skipping connectors-ddl snapshot apply (BOOTSTRAP_SKIP_SNAPSHOT=1, generation mode) ==="
  exit 0
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DDL_DIR="${SCRIPT_DIR}/connectors-ddl"

# INVARIANT: named, not globbed. A file the snapshot should no longer carry —
# a connector's bronze above all — must not be applied just because it survived
# a bad merge.
SNAPSHOT_FILES=(identity staging silver insight)

source "${SCRIPT_DIR}/lib/ch-exec.sh"

WORKDIR="$(mktemp -d)"
trap 'rm -rf "${WORKDIR}"' EXIT

split_statements() {
  local file="$1" prefix="$2"
  awk -v out="${WORKDIR}/${prefix}" 'BEGIN { RS = "" } { print $0 > sprintf("%s-%04d.sql", out, NR) }' "${file}"
}

echo "=== Applying connectors-ddl snapshot ==="
index=0
for base in "${SNAPSHOT_FILES[@]}"; do
  file="${DDL_DIR}/${base}.sql"
  [[ -f "${file}" ]] || { echo "ERROR: ${file} is missing from the snapshot" >&2; exit 1; }
  split_statements "${file}" "$(printf '%03d' "${index}")-${base}"
  index=$((index + 1))
done

pass=0
while true; do
  pass=$((pass + 1))
  progress=0
  remaining=0
  for stmt in "${WORKDIR}"/*.sql; do
    [[ -e "${stmt}" ]] || break
    if run_ch < "${stmt}" > /dev/null 2> "${stmt}.err"; then
      rm -f "${stmt}" "${stmt}.err"
      progress=$((progress + 1))
    else
      remaining=$((remaining + 1))
    fi
  done
  echo "  pass ${pass}: applied ${progress}, remaining ${remaining}"
  [[ "${remaining}" -eq 0 ]] && break
  if [[ "${progress}" -eq 0 ]]; then
    echo "ERROR: ${remaining} statement(s) failed with no progress:" >&2
    for err in "${WORKDIR}"/*.err; do
      echo "--- $(basename "${err%.err}")" >&2
      head -n 3 "${err}" >&2
    done
    exit 1
  fi
done

echo "=== connectors-ddl snapshot applied ==="
