//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "account_person_map")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Binary(16)")]
    pub insight_tenant_id: Vec<u8>,
    #[sea_orm(primary_key, auto_increment = false)]
    pub insight_source_type: String,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Binary(16)")]
    pub insight_source_id: Vec<u8>,
    #[sea_orm(primary_key, auto_increment = false)]
    pub source_account_id: String,
    #[sea_orm(column_type = "Binary(16)")]
    pub person_id: Vec<u8>,
    #[sea_orm(column_type = "Binary(16)")]
    pub author_person_id: Vec<u8>,
    pub reason: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub valid_from: DateTimeUtc,
    pub valid_to: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
