//! `SeaORM` entities for the identity store (MariaDB, `identity` database).
//!
//! Generated by `sea-orm-cli generate entity` from the live schema, then placed
//! here. Note: `binary(16)` UUID columns come through as `Vec<u8>` (raw 16
//! bytes) — SeaORM does not auto-map `binary(16)` ↔ `Uuid`, so we keep the raw
//! bytes here and convert to `Uuid` at the response boundary.

pub mod persons;
