//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "persons")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u64,
    pub value_type: String,
    pub insight_source_type: String,
    #[sea_orm(column_type = "Binary(16)")]
    pub insight_source_id: Vec<u8>,
    #[sea_orm(column_type = "Binary(16)")]
    pub insight_tenant_id: Vec<u8>,
    pub value_id: Option<String>,
    pub value_full_text: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub value: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub value_effective: Option<String>,
    pub value_hash: Option<String>,
    #[sea_orm(column_type = "Binary(16)")]
    pub person_id: Vec<u8>,
    #[sea_orm(column_type = "Binary(16)")]
    pub author_person_id: Vec<u8>,
    #[sea_orm(column_type = "Text", nullable)]
    pub reason: Option<String>,
    pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
