redisOperator:
  watchNamespace: redis
  webhook: true
  imagePullPolicy: IfNotPresent

resources:
  requests:
    cpu: 50m
    memory: 256Mi
  limits:
    cpu: 250m
    memory: 512Mi

replicas: 1

rbac:
  enabled: true
  scope: cluster

certmanager:
  enabled: false

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 65532
  runAsGroup: 65532

securityContext:
  allowPrivilegeEscalation: false
  runAsNonRoot: true
  runAsUser: 65532
  runAsGroup: 65532
  capabilities:
    drop:
      - ALL
