apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: clickhouse-default-credentials
  namespace: clickhouse
spec:
  encryptedData:
    password: AgCgFw04BDzE7P42uAeQQ5bymYWWXnfyuQo++yo+u5XesOlRiJVaWtC4VtDoaJGqA7pjMLPbQVxOzIMzt5TPJtMkzLelhpjxEKGNv4XUutW2owPXVuEYGSUVqdKydOkn+jvqdBLLE5aN99U+xIKkGc2B2QJCrmpZQ5BKA4DiDbH7KyDWevmqmeAGfTu5gOXV1WkbFSuz7juQ8epfXnCyB5lRcKt0CFy4pvDp0/7r3dUOquG6mTCd9kRpJqCeIEtBS2L3eZG9c0EGwGgLiwk3cdNjfoX5z/TPB/9ejCG26ZIIvd8iZxMHy1Tdb+5OVnK6YAyyuQHgAC3sQrxtRLrGQJ9JhYienH1KiUZpNY79Gjf8QSeWRo4QLscq8LCvftpKGhR4XLSpOtPWq7JIYnCSpa3TNdM9Oy1j0tFvmkc5PemCD+m17eX+xiWziUNh8176TBcxVjpSa908iFc5iH1UIKHOakpLdu3GgBCmhg+6ITCOpfgqKUENQHBoLEfHQzbVzD9RbjqAjC3BMV/fbUDixvZ2Pt3YJwanz/6RQOvT3PzoRnmW14vrCy08gJ8IXnDV5fMCCvOZihDtsHmeys+2u51x9IG38bBjXFY1pkxvxwJOYMXxgaslo1UWAazq0m9NyJvo78pK1/JSBHKeuDQMrLaeZM6xp/KxFZGtNvQrEyuGknx6qy1tMBrEc/I3keFepex42TMicAWuk0TlnLmT7A12sx/llwwZtMDfkv617rcOI62zQUagjE/+RGQAtBFPoVi70fzxIWfK5SlQKvgkzbhA
  template:
    metadata:
      name: clickhouse-default-credentials
      namespace: clickhouse
    type: Opaque
