apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: clickhouse-insight-credentials
  namespace: clickhouse
spec:
  encryptedData:
    password: AgAJlQG1CBhBJmHHDcHwLk0dU8g8BSCT/GK5DIIPZtFc4BdyG7FbP70YAcRrOY57ZwkISN1PjAOrNQoe/Ghopq/fSr+LlPyZFm2vjmAP8eDM5HVOJPI38+KzsTlgRualBcK3CW7C9SEr0N9yJcoLwMF3I1D5kF0s1mVQGwHWiefUwmLNbYu2a0qK0NeTSLEm2fj20FnB8CHQihWnF3on2mWypGsjYfiPH1Zi89/tFlnTOuEI1iynvENlMPQw71Ox66Cs4MGknU1cpF2F7qNba37mJg6+22EFoxXd6D2jJoyeVt2M7s+pSQoItpviJfswbhJdExFrJqRBkI3QW2AVBvb5gKvSKowdKSmRFjtBtBh4xs0f4pm/6MRngKHcwOfOng4ownEEzCL+UcS+SBRM3//7hn32AYqZD4KWoxg9Qc2g9c7eGUPY4Qljk5NPR9LO0k//4LY3X/Y0D0jtP5ZXqVpoiG+bq+Ml6Ne6dt0Fj7LDuUlP1M8ZXumpN76OusQUSa5Qb/L/TNwB6UVwcskA4xJfZPO2vZWN/XSO0FaE8oG2m7wSca2zRytxlKZY1LOjUPjMjO2aPJVqOQWSDGdXqF5LdSRDdTs5W0/L77VVpF0nyu1zYm7M64BKzR16xa8iHBavn6eyk8tnrdRfYDdJmUGKwmHkdzb8Vi8O0qPwUzhqDy9OzNFeBqIGnZ1S7sVquh8o08OoulHWWTANG+EnbrS4KqBAx2chaNrKhkyJn4VCQr0Pbp6qQIOuqkrUmnY6brFuVLWEw+PRF9qsz/gYTdM7
  template:
    metadata:
      name: clickhouse-insight-credentials
      namespace: clickhouse
    type: Opaque
