apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mariadb-insight-credentials
  namespace: mariadb
spec:
  encryptedData:
    password: AgCSGDIFU1/9MaFUrCssZvHY6loHO8o3qLpwSKDY8vHVgtiKbsrH2dEdirrw5oN0Tewd0AP3bgv3q9xtZvxRh+aCD6pDeatqv5DCJ9PlvsBVTZih8e1N3bTVM5T6tGklsZDDbvM7aa/Wlt5fNr6D044qfTvQbsBgZUQ9Lq6Kl3f8QyfSEfSfaKTkplGY0cYulnAbtXIZOs0zRUdO9wbsyXqxWAt9EibpC0pHS9nwOB0Zjy6e+w0jtObR9dlfp+cb8auNZf/iVRzRV38+mbYfq67nWg/VbcpKPkYrrR9BHnpzdJCG25TgNDS7tIKQohDMBr7QtRXtTRULjL+IzQC70yaiJq/0dbd+iBQie64+yn14KRGDQHjipPAE1fLyaVjCA/dpCB07tOFpfLi4xbwmqMXoKXkGziUEM0MbJdYTcoxgBT3V/IwUO+qxYtxXSHMjitf+/Q8kHcBzQx7H83R0k2N0eq1t904BWmJd8PD5IrT3epFNHRBqlft8ryr/XEXHZxeHX4h1JO4tLqdZuu0xSA3Ud0VfTs/hXhcEb/XFj96ctPdzdXA1x8J2xz1YXo7ks+6M6yM9TWpkjKMzFb2D98OKEkMKlLYpffaVZeZcobEhXepF+Ccb7gpr7jDuauqsyt6kQg8MZ0jsnohcxNKmUDVmk12y0wPEB5iECU4iiO598HQE24cdkgikaBn2FqoXATCJBHYNjRKwciAeSE6dvfcC9HMlUrTeFY6BQuukfpoNmiSzwXP96XwETPwo7ERiiFSDa2zXdpt1BT8KSLvjQYKP
  template:
    metadata:
      name: mariadb-insight-credentials
      namespace: mariadb
    type: Opaque
