apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mariadb-root
  namespace: mariadb
spec:
  encryptedData:
    password: AgCICrTBAL49oVpfpzfnu2aHLwviGreNOxPhWV9hQvXWLzoIUSrAX77aUpdwKPGUynw0gmHcD8MiFNWcryTxG+jU75+TsNewfFdfRq0JpwJriMCeSlBa0odhzZNSCRYyyT882fpJy37n/yxNANUG71WhDGv79ai4We9rV6qVU5B8C1TBHaToecss51/WdggMdGprMbw2uM8h26uugExdoavlFySvqgme9XIHcLDvhDg5ZcM1HIUpXxyfqpBsh0HOfvki49buloCsv3HOt8yKpSfY81cSgUuFgsqp5E5QxvU4wbibEH7gK6GGoygU4/UvTPgybzLq0LcZljeKRhu5KwDxnhlIRY2rw66ebmCilN+iecd8eDfH7+W2zbRGDKsYR68N2fGLu2vD1DA99c0zSMg5RJOlWJ1d+spba+rX0SWus8+NkMVNtfv6RmSR/RK/4fmb9i5X58nrvg+aT7NoRATrYA/oTF5W5yDhJHDWv3butjEaf97Suk7IvijcJB193CgN7tL0FVGSdoslHOHDfPQMGfemfYzixZi8XYbZePQl2zk0l1TXROcucbLu6yHo/ui/43qU1+LtX/u7ygMF+fNGp6t5vZLQ21B5BRGrPMdNVQmCh5oc2oe25nO18CiVvVA2sKyF8uF3F6VVFU93vZbzFt4moqZzoJ4WWHW41v2IBBl/mpcgxeId9rZl/Aklb3xCo/IPMnSrGhPRNRg8valsAPp5i41S8VjD5exHv+39sCG6E5rZ8JJlLDGKl2ZAiXE+g7h/7BmawaU+/oyIFb77
  template:
    metadata:
      name: mariadb-root
      namespace: mariadb
    type: Opaque
