apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github-oauth
  namespace: insight
spec:
  encryptedData:
    client-id: AgA6JxqQskJjtg8bHeLnd5zgNDNc/hYBDfPAPDqxVkPXbHc4lu1skX3XGaUQ0Z3Lq868YdPtvQhzjR9nJOD4LOftKG3Pe/ScIWJ/zbNL/7/DZHj2EOMltvZOUsmGr1eru8eyEouwAOsvK4zfO5gHON4s4i8DfYusVyBhWPUAjjrkhtI4V13R8UEdB4DRFAfVICngfc3217T8zPf+ABKscsODDUr0AwgV+tFzI7dTAy7V1GdSexyBF8hcpqqMZSits9khKjj3f8OtaxIhb/z5sy8PtEROjQzA8Mbq3S585YaQwStipMUf370CoYjRLu1PD5IyAhVFPMFFBUXXw5+Bz94pNzK34nRbEpi7wc/i4kiSOAt/rZEjOYjjdk4hbyouHVau9sgXqQglpKu1+veYsQ1X408dEzfpgkRpyIGGUo0b2ct2SMwrc4RL2GEnEReoyW3VWofp3gxvZQhoh7uUU7EyfTnlT3anMDmgGMxiYz+OouXnL1Q9hmA5jSgqM9ussuaGUBtjeV5E5pqDvEcLbHaeExalKwh9ZaSkwXM2mrGna7LPBGPaznrL2xOvi2rZeH3rIjGfHsq4+TEbCEs7eytnSYGl4OuUCMXxunHAlOxH9hpsTU0dLxjkGnNYtojDA7OTSzE1v0LXNeU7C1sh4ZH350y9DK7O2weddoHOmyB8zD7pxQGOJjBJ4cevKbTEFO9oR5Orb4r8Az+04FzJ01QbpYShRw==
    client-secret: AgBwJAqPmnnr93K2w4+w7vTDEJIto5A9kIHoZ4wr7kXS3werQmBsbhndaquYF9Mw7nXnOi0sFfGcBxe6ap7qKwtoteE6vEpFUb5XFFNVAk/LaqStGnKGhzqjc8KW0sz8q/U9FjJT0bzoYJgC15btiyHJd4O7Ry/L0DsJYpzP8s3fCGVF83WcuzcD46hhkGpj8LhQSYtFJm2pun7Ju/Kw8g8uWjnbKZEFHFZNNCLTLGRzMEo+TubFave3+vVybWihvafRn432pZ8irvI0x7b7dPPTOiMrsSVfNiM06ajLVYdcMFCe64c1QJXg4l0t9DrnfvA52BRfRYLglr2QFltLeewW/Hsm3JegbaXlvqNOdbI4gSWEfx6lBUCv7aYGEms8SkJxnNUZFecRQ139FmhNYChfo3cQ8FUX5tMdA3TlKmoSJ3dlWr0AKNu0KkH0kNOPdeUSLvmd4yEtgxINILRORCMacKJrFoBgPerU19AKVJy5e4C+6aljaMUKUv5A1ioB+B9GEYe8ZlEN+cDo+Bc6zdgmkPB1Fvuj0sj5XQ7cyquU6X0Ozh8LbiGatnr6Pa/6gday27jRm5bHuklVR+BSBTJwHR3OsbHyFR9t9ztbiVU6+XwjcZ2/jtlcyQqdtTJ+k+rmcA2RWKEEdjX0Vn5nos6WfgrubvaV+UnTQn1rbISlv7JjqKfh4W62VxLbsQv6mpXFEyzwYluI9M6s9ORLwSomaijZnNBGcRVF2qfA2lnbS8Epm0mA32wZ
  template:
    metadata:
      name: github-oauth
      namespace: insight
    type: Opaque
