---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github-oauth
  namespace: insight
spec:
  encryptedData:
    client-id: AgAwP/TK/26wlq9VRgrX9FYbCMDdmNSXef/T+55aNNtTDC2lgn22WWpgG68xYqrnPW1QhGsG4/TuAPL/j0XrjG/Mo4aGRq485PPC6+Iw2jqu4lvJh2T5zgc8AY2ooQWd4lSNmAPqLqIzAPKNdWk3ITiu3onCfiFVxzvtEhdyl2HU3mvc1cHP4cHvL+SIryVQn539UDWxmQBIwvY5V3k4MOb0FE0YtV5Yror2sGBTrA/E+ljMdQ2mmtIlRW+JXYah71n3qB90PpuXKwQmC1W5y/KG+dEBOyZg+TeyW3ZiGMpuYE8WUL2Mz5bi/RpZS0Y7CTo038tLKLNW3udWtuL/y3v/oDMQiMAQX7tmFM+MKGctOgkrDfNdvsqW3ikSNZ8PsU5aRYfycl1IdbDKxrEYgeOE+gs4wIjp2gX8AxkP5n2ceszb1SOHBOKNIMWGYEXMtHzkbRbXTGjcoYW942k0SPgy84BALdOUSbbP9RdgMeq+6/QGsj7YJ36mAEZRIkLa9tX3W/RD0YF39k12XpufBpaLGtazQgu6IixTgOzZtPckhvSa/LTGKx/31OB3MhsybfxxBDkXJI+80xz2HGB67dyoROJHYtEzO24cj+5Ksdt5VZaDHl0hM6d0FYRTVt/RBddg/Esyjl/tbfPBWHtDMxhygCMzx6bGRI7pU3yLZt6eyFmUJ77UVgWKfWDGdIb9HLHu4KdyOB5seF9FXrCtUyx8Dbgf9g==
    client-secret: AgBSJTFdEKV/5mTZ+5CbuufKRDA8zzuqEkrBVKIM6lQvEP5wV9cNZglnlDScGaIDq6F04KiUz63zu4mRtEWZe6qwpbkWX4g3N/tba/Nl367mKO6z3RLQUb4uZOpwwQXgZrr4RTaainas20R3VWxZMnamp5izsoMgbbyQ8CXDeV9wzQSV4YjkjVwWCoYJNS6/LgJcJiEVX14GpCwC195Xvmf843ACv007KrcUvSmE6PfvVAyM0rRWoZkDViYtVlUnXISg/90mEHZ56lhKt8Bp3xDb91hopKy8vYcH8XZ3ajI4Y97h7/Vj+9rz5n5PKER6CuMPgrvfMsz4ZGLPD0DliktShwyGSUyLZ7B0wT5pHBaZOzWLNix06R/GwSoz9V6mWEZUAc4GuORUW6CbKF8c2uMVhmqycgn+tmlezj9+IMt+T/kEEuDUfluWyujRS+BtaCO03p3tNb6jdg2/NJLWb63GBd5ngFo5kruhSKjmeqfREO5ZEeoRg+Zew/3eo3TR3+MCnPpJR+NnI9e+bLDZx8c5sNw2InEFS4ul0VqzRC0OKSD76Zje42mD7h64wyvCAHGYQqJX7SvuBTKC/Ggks82AEtNy7n/UFPxafuoBHz3+eZRlgnlSXzce+O6R+zr8AhI9f+VvU6P4u1D5C15AjI6HkiO/e0CiTD+ceiwIq3V/7m8d9s7IFO+7ELuZlJ6S1zlLb744WCNYkhvGciQJp5d5AC3JMOJk6lyvUmym/KH32PmKNPXe+KNM
  template:
    metadata:
      name: github-oauth
      namespace: insight
    type: Opaque
