---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github-oauth
  namespace: insight
spec:
  encryptedData:
    client-id: AgCyuLCRVVqcIpdDdD5RYkPNwfMynelzV3AT838bX0q/+6tSNJnQX7WMsOVhzqFRY91fT2PB8vI8V9YmRARDunypiojrU6rAj0NZ9oy10XY0exNyO7ylr/FA9YJTC2em4C9PvcZdsLg+2NHxyfk5LVu/y5IjjnFYjqdr4k/UV3qR1t0CuuAhOJ5RR4zLp8IXcNK7tuUcRkJYp0/PfYhjC1JIBgUSJ85It4haIeBOaxXiMEdZu9NskEXqrAGmv4WbHCi845b7G/GVWnzOioD5/as8rDdZ9jeLDBwL0L9pD095ebVdgdM6DvZGWJZltV0/fYglgkBrWPJj4Je2lIcxj0qJvOBgApLAL+tkUUPq32GfoVAV5moVcXz/4I4eQ2fRExD9Ujo0aNDojS2055m9KSKYkwT1al1p+6OGftHfp1ORloBGOKxU2c5bPtWO+GfU/2B9YHNoAlCS5RtdWmNSb7Nq1PkT5AHgB6ftz42sKwFFwiDQ9+cu7dwS3O+Z48QPKTO05jm1b5m6jq5Hdcay9ErcloRSy3QIDI+t7RZk0h9PkKQXZdomoClke4EMvGBWdgWYnd217brTCfn/p4JUIyeXJ2nmYDAkoYN0Nr1bQMz2NktBYtqLTkiG93ku3RhU0BG9RYF8EcE19+KhUXcAc2MJ5VWQyM1pCgUS/2fsXouL9mYr1CjYEC05YCZwFcrKO9ocBxcpntGzE/a8n3dMY+TuW6hvdw==
    client-secret: AgA/hsC6J/2adH3CS/UuiX3p00LIspojF3LAJG0CtxV0Fjm6GMgsWyoIT4C2DnM8VQQLKsRN9yKfMDbWF5tL8J1pWPgRdLoZjnsFW7Zwczqlf6LLja94F+nqd+RiFXfw+MhA0ifvcicX6ik/OkIKlfUJD8u8o4WZPcbd4Vwt0kKse0t36N8ViDMmilB6h398uXz5Mr+PwPTmfOiyTFeWsdHWZUuHyTiCqs3kI4fmfdcST7X34rfZFtI8CucD0fMsFQf5jEPe1/nk2P1hDMbKZRhDPqJpkGEmSotK/UhvWtK88Mp5GW41V+eajItQy1aja3TBxFqYFfsxWJ4GLtjY2F+p9IBVDHDhwycoahUBA6ASd4xP/nW94dGCr925a3l83b/W9dlX6oiGIfE3VPKqwyCD4joERQSTlES3YwO5+iFMbIv5n6plDxCE7h+zC6YIISIMCQCBeiYVxPgjkP3Ug1MOpV8qBvQ2Mcv8uCc4He3IP05dT5RZ6GTKlN2Zg3XcoE3nk6KWROkV6LNLRzgwmxLkJNRbFdDlPUwh+V2ijuSayLvF+3lGmRJuYXqUy/Cgx3eTWq55aB9oJXye7kYqipX6WZo65gRvhakR5G4iMFnbelCuctCBTupSpQqI1sZc25e8rIQh0e7eMpKMWAi66BOD2UpFuxU3qPvXE/Zml3kFPZmIfJU5CQhsuURpiy6tCGY4wsI5MrCx4+oG7JwId/1RsK7HVbj2HyOo/QEnusFg2I9Qoqg0pTHw
  template:
    metadata:
      name: github-oauth
      namespace: insight
    type: Opaque
