apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: insight-oidc
  namespace: insight
spec:
  encryptedData:
    client-secret: AgA4AzYfAdVY+WE5Xw18Bi/wCa0yQ6saaiRjImVY8/3Pd+8fLMCgYBgLebWiNdPZVjuEMaXLUCviY/CECcYt1lf5y4vU4uvqupXNbG+iD8qeFbzopmX7W5J4YmAkkS+yiVAnPG5qi/zc1l/TSW/qNNjd2eXDE+9ohvA/xsDf2rvBytYaslWGfOzMefIXbOW6Pdi7hHibrgAoQgYQRaaYtYqv7OkPefAhBc/vcpEK7KBtgcFwTBZVP0WX80nz9DkgVYRPw+E0xdPuGjnpLULSuarhCLcyDpnDAR05DYYVv4g1EiaLDxMaylPVL5/Jcq5n2+VsH1jMv8MWhY5Lsyv4969ZZKNPvjEfL8Q5EvNc5s3lUvi7pBHNumFKG2B0x+/Ar4VDiMm/RVQlSEtjTvOEzCp5bJxLjy/pk0wFe03VzW5Qc0bCX/pb5P0Z1QP8CW3WK45srlGPOGV5M+udXx4hNNhUOaEU4KVSj09x7wzdxmXblRFaBESzu7QCIahacmy7hX5MPTT00yUcW6YxjPyhx8mE9Mz/hiDGtot5LkKUgyptVvjRybf69KYJ7iOvo1Vxfj3JS7iIIdPinDO/llCBZZZ20YaicacICNJmJmBW6+YinYv9Fqnqr9SvPpAejZLZoDcLVpgH2KmfSTS4Kk5IjCXCUE6lGUBmwSFgJxMHVSEKgV/BxM4R9LaCDq3liuoYV+eocuIjA0iSFEj6AsB7iTP+D+4zErUcGQHDuC8se5GR8pRxlcik5HgdhBXT9/xUqLOBT+89X9AJP7xh9to1PUK6
  template:
    metadata:
      name: insight-oidc
      namespace: insight
    type: Opaque
