---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: insight-github-directory-main
  namespace: insight
spec:
  encryptedData:
    github_organizations: AgA6V6KHj/t6qdXiWmwMDSE4Wu12mTcjACFc2JaOPmXipdsIFc+Iju8+t0bm2puBhUK/Fmun3z5xBRLOw1YOf8TKLH50HzGUDESGJKToIeeoElLDpING1uKO4llSZj6/qVPNX3lPhosFP0c4VnblJuUyuj+rCMpyzw2tOhro1CRUP7GxT/XZRtxxkgND/KHVKio2dpnrJREtqrie3MYy3EszE833T4v1OoJbSuoX+O8AppJYkKTwVLJvcp6Yau4G7wZ2pZesL7vo3xE9Jh7Lx7BviQUzMyI8U64eeTBR4MC3KC1o0CqY5GAerXJ/wdhmi/6iY/6J9Xt+DcNSMhB0BWPDUhVOhYpVZYB+2ZQiaL8X3O8tnaamNs+Q/kZ5N/7X/evMTA7W/HWKCTZdw6OIcBagIIfl3eglvIHzr2/UiBd/wqu6j493Z5H/e+/dwDQEv+NVedrjzi/Tfv5qxnu1XYU0xDvTV/senmsfTc6RfpVVmZ+eEIFlVelEHNv9RtgKEUo9qOCMr+aomar9agYlTCfyu7hh0h9/Bs1csIGVqwS8ZbcP3X71KB+/U1nPfWCFRquUHD/qn+gt8ESrnPXO3ZCk99v84AEnaswDhhNsQQXMxpPTCnkUzL/oPuVjPUw6eSkvWDFvTWxPR34vseT/MN4Ku56AzCo/drLv23Rt9g2xa8mkF/grMSNA4c5t+OR6JGG/8cCvUodzufH0hEVgR+MKLx+v
    github_token: AgBDqCda29gZYqJeWa/eJ5H6+OZJkeiS0BqGbXySEQNJww1UABN/F1xHEjbiUj7yoEFD3VAZMT1htmqG0PKsHp7oJGC5azxMMPG/FLimJx3yEQihyJJlIWQpNt7qR0t2UDyT745qPsn5ReziW34J6x5ZfnUqifH4VA6IWikr8GCoiitGLdnj+XbZMeV9L2jaDohZX40KpI55mxnlRUlR1IQ66msyFAMaP95nWafyxaf925utS0IrPrB29Ajd5wQLBrLNmVE5sN5vcwGtCXqX9xme1HTqpCYULQvNX2npkypc9nG1drU3/6HK/rOYf9YwJgPGAcmdSMX1WulYmWa+435AjeRIYgttG8/80nsJPe6jpDYEOdctWtW4eif1DKZ8X6oRG+YLjteDj5oQ89CjPwgytF0/QsAsjcB8qXMwOzByTJEGu1jw2Iw64YLg0OwE6uNpZ6FnwEQVO08JCyL/4RR7CCtNtLZGdWJTBZcImJRyEVl0EHPNxRZsPHgkF6airj6ezhEMbNLDRW40SyFz/2SQeYU/SO4vQeM6/XecoePsVuXYX8KohLJ9aBLT3PKLr4sB1a16efi2Ree2dSwoC4EDvq74ridChGLNeBzjswWhlU/YmtO1NHnbRdmtPHawcGZOvZhsfmEM/WNgxpciKsv0y4ZRHZiS1C0PXy17LI6K87uJiPpW93EvUVpeTD2mPrNAMKd6oys2ucG2dqFtBHORDXmTv9TDLeoHkWnQLQfZivYnukdRtgYn
  template:
    metadata:
      annotations:
        insight.cyberfabric.com/connector: github-directory
        insight.cyberfabric.com/source-id: github-directory-main
      labels:
        app.kubernetes.io/part-of: insight
      name: insight-github-directory-main
      namespace: insight
    type: Opaque
