---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: insight-github-directory-main
  namespace: insight
spec:
  encryptedData:
    github_organizations: AgA6V6KHj/t6qdXiWmwMDSE4Wu12mTcjACFc2JaOPmXipdsIFc+Iju8+t0bm2puBhUK/Fmun3z5xBRLOw1YOf8TKLH50HzGUDESGJKToIeeoElLDpING1uKO4llSZj6/qVPNX3lPhosFP0c4VnblJuUyuj+rCMpyzw2tOhro1CRUP7GxT/XZRtxxkgND/KHVKio2dpnrJREtqrie3MYy3EszE833T4v1OoJbSuoX+O8AppJYkKTwVLJvcp6Yau4G7wZ2pZesL7vo3xE9Jh7Lx7BviQUzMyI8U64eeTBR4MC3KC1o0CqY5GAerXJ/wdhmi/6iY/6J9Xt+DcNSMhB0BWPDUhVOhYpVZYB+2ZQiaL8X3O8tnaamNs+Q/kZ5N/7X/evMTA7W/HWKCTZdw6OIcBagIIfl3eglvIHzr2/UiBd/wqu6j493Z5H/e+/dwDQEv+NVedrjzi/Tfv5qxnu1XYU0xDvTV/senmsfTc6RfpVVmZ+eEIFlVelEHNv9RtgKEUo9qOCMr+aomar9agYlTCfyu7hh0h9/Bs1csIGVqwS8ZbcP3X71KB+/U1nPfWCFRquUHD/qn+gt8ESrnPXO3ZCk99v84AEnaswDhhNsQQXMxpPTCnkUzL/oPuVjPUw6eSkvWDFvTWxPR34vseT/MN4Ku56AzCo/drLv23Rt9g2xa8mkF/grMSNA4c5t+OR6JGG/8cCvUodzufH0hEVgR+MKLx+v
    github_token: AgCwQyYFAWKP++SQtb/qlclaebbFZSbAiHd7eHk6vlOCox4HGPYhXoRX8jgii1o/ONIOxiXYTBMbkGd8hv9A6z4rVoGeAYSWBDM5Ikl2g99yEah3xu9vRd7EO1ooC6WpwNbH+DyDJXvVnQLd1ZvlbqHvtk7n4DiF5+wCSK0qg6QySvBcIHgGg9RxUSw/NQgeDUXV2mEuTYtYqz93j7iw12o8LicGPIcTKG9CDHEua65N7XCFy1QVlh5R3hj89WvfDMf0taiJ/qXm7LyeYlGrG1+V7XXKCuUVCDYXodYfEzW3M1VDYqcHmS5FciAepnYT9rj0CUWR24CLbAX8XEI9MY9QHu5CUhhnpiMe+0anUvz2hshOd/q+IWgZe/Mg9oGFFofQ0WmXJHwwcatuu19tgP81gifpgqhk2OUPyrvylh2+WR7k2TGx27OOrgEhPm+eCoakQNUglEKddQAovTpQA3hNHl8aLYyFMCcwwyednP76eDKG/MZw83j3XDrasW2qLGd4YQZT2kOE9J4Ca+M8fXhBEX05GXAPchUQzM/uVnpTo7nALi9Ii4vfz7jCpzWldB/oIRcHxVkSSODkB4r2qCBUVOpDC6b7UfcSdyJrj6//Sdmk1ft8czOcTYnM7lu0NbpAtIhW3U+9KFX9OkznDtBHLos9IX/9Dkb1V0HZjCYhesrgbgru2FyFbRH1hCcz0mW9bcY3RZwFyRyzTKKRDrvyz7kIu7fMwmV7efXD19pDKcHYW+EAfL1I
  template:
    metadata:
      annotations:
        insight.cyberfabric.com/connector: github-directory
        insight.cyberfabric.com/source-id: github-directory-main
      labels:
        app.kubernetes.io/part-of: insight
      name: insight-github-directory-main
      namespace: insight
    type: Opaque
