apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: insight-authenticator-signing-keys
  namespace: insight
spec:
  encryptedData:
    current.pem: AgB3WdwXVi5yarRziNhU/hpCHrL158WUYVONeW5PCfybKP1tricugv0UuLVMdvAchoYSEFwn95RBtuzJPdqOpigVSqJhwg7BHaonx3fO7okXkL2qIHiLfRaOJvVpI7j/Y4hGTBzBI12gBdM2eTAHGfQ2g5M3law1w17eHmoS5SV/OLfBb5ZCdKQuGoYqnWucwHvnEeKL2y5kICwDmW7tYA9XkYRGrDuyGHwfyjJwZDNvD8nKtX8ewNLUzFZ+VyyG2vs1pEl4cDYvinVXFoBQQrNkrFZBF/P0M5zDseELO/JqlrT3RqcnkRWJbNAmdJ3L4sZwHzV1YbM411DBQfHxgHPclLFFG66FdeWZ2cHK/O83pic5gtWVmLaGFj6bgCU1oW9J5quJFOjoIJAAR88z+5KDGAYHTbm0uCj5dH7Z5CDSZc8I0lJmsHCrRZDjgMAwbU0aOM25eAeMJ/7Cu66N/JPWOz8/v8fjMHaET4toNTwXLDuRjWU/TCT6CnDscMghOi+8y93Ex1j9k+n5HK0FX/gQQbxm54DYYQYyCGSMEVVc1jNFq3OfJqKlRCf1E6umqYzijdWjzSh4LT5d8Ltp5ynjZhCsQZLkUd3Qiiq+FIK96My9HNqW8U5Qb1jCTPENYvF/EJQQWWlYCl98/x9exY/Tuecc2sCLh1P/znGWYOyiR0dmh9UcsHuWzNszv4/SP+GsPZM1Ypnxh7sl0a0RVh/c1sUaHYSuF5+sQqJ5jwArlXjJuUg2JrJ5wKa+IjkoCB7en1JGgOK6ZNEH9zStsKaNrP5cfXGP+pk9fL21G51qLjk+Pg1qMmIjMHZrqRbW+oYBqNEGRq946aiuV6frr9DXLX8SUx1PhIbetFiiqBVzfqguAHJZyFEzm0IBFVTUfVSC1DxmPe02GlMHyKTCB0IoKUnbi2kgUo1NTm0mGVr32CdS9h7OoSGmS1YI2zxd0O8YcLFNW8co3FW230dZFHn/+ePuDxZ3v1e3GAK4RB00KlmL8zrvp3RfJMrjikDo4Iz3
  template:
    metadata:
      name: insight-authenticator-signing-keys
      namespace: insight
    type: Opaque
