---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: insight-github-directory-main
  namespace: insight
spec:
  encryptedData:
    github_organizations: AgC3v4eOXRR3+pMvDbhPLey0tqseELv7cuYt0YEWHsq5ieQJlErYUKbFvGcKWXKv1wb1Zn2VNmCvOujb1Atlj8/7zEdRKib94H5wWQdIloxclAfZse6zcfKjBPskSAtEJ+6xYa8XKJV7lJFXkvSILOkEBZ94L4jkeSIeZo5h743+BvSGlXn7iFtOl/n9M32QH2TX8ZAilBUKZLOIFG+A0TlYqapTHB08WqRZYmk50QoZkoUNJ3DlzCTN8QYqYS9n4UaWr7thzDEtNwE1JhNkCRdcN9NeUElboCGHkg88x89LFS9PRXK2UQJ3ftY7G9MDXfphExmOCRZmRnj4LYrIr5QOHraU817P6Q1vo5F1n1v9Nk/iquhixvOLAZM2CDMZVkKhIuqYmcG5MlRsDZAtAlY9Sr2OSg0a9GvTjtF6Lq7H/6nYdQmh1cdHYbW2pm4UQaRW8VLXT/daJd0mnRTRsrqu3lnNhkILEC1PULJieR6sJHMeY3kit7QGUxbRAA7Caymg9/N5Xu42MwKENo9U6qajz4KEK6S2QIFcVKFadpg3nmMcQd4YvUkWtmKMONhYOWgl8tEEY1+GDkjrlYpKttb7HuPSKQxOu3+CH70WHb2DIpBLoBkR7IjWKpYwTnxQl+sl/U8Ds32lZVJ1DhfOboVA4sCP0+dgr9mozOnLZacFTzDRt9f1c/sW7t35+Hqu9MwILHfMEK6szIhaBRdvdNvVpcHn1U0=
    github_token: AgBDqCda29gZYqJeWa/eJ5H6+OZJkeiS0BqGbXySEQNJww1UABN/F1xHEjbiUj7yoEFD3VAZMT1htmqG0PKsHp7oJGC5azxMMPG/FLimJx3yEQihyJJlIWQpNt7qR0t2UDyT745qPsn5ReziW34J6x5ZfnUqifH4VA6IWikr8GCoiitGLdnj+XbZMeV9L2jaDohZX40KpI55mxnlRUlR1IQ66msyFAMaP95nWafyxaf925utS0IrPrB29Ajd5wQLBrLNmVE5sN5vcwGtCXqX9xme1HTqpCYULQvNX2npkypc9nG1drU3/6HK/rOYf9YwJgPGAcmdSMX1WulYmWa+435AjeRIYgttG8/80nsJPe6jpDYEOdctWtW4eif1DKZ8X6oRG+YLjteDj5oQ89CjPwgytF0/QsAsjcB8qXMwOzByTJEGu1jw2Iw64YLg0OwE6uNpZ6FnwEQVO08JCyL/4RR7CCtNtLZGdWJTBZcImJRyEVl0EHPNxRZsPHgkF6airj6ezhEMbNLDRW40SyFz/2SQeYU/SO4vQeM6/XecoePsVuXYX8KohLJ9aBLT3PKLr4sB1a16efi2Ree2dSwoC4EDvq74ridChGLNeBzjswWhlU/YmtO1NHnbRdmtPHawcGZOvZhsfmEM/WNgxpciKsv0y4ZRHZiS1C0PXy17LI6K87uJiPpW93EvUVpeTD2mPrNAMKd6oys2ucG2dqFtBHORDXmTv9TDLeoHkWnQLQfZivYnukdRtgYn
  template:
    metadata:
      annotations:
        insight.cyberfabric.com/connector: github-directory
        insight.cyberfabric.com/source-id: github-directory-main
      labels:
        app.kubernetes.io/part-of: insight
      name: insight-github-directory-main
      namespace: insight
    type: Opaque
