apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: insight-keycloak-admin
  namespace: insight
spec:
  encryptedData:
    password: AgA224ca+ksBU5kJtB2UcGYkbNL6Gr0nYw4D5Bjg2tSgZDcICnNeRYRv+V9aM14JipV83Jja4+OPPOj7GVvo0cbLW912C08JyScFaT8PDLon8pIj8Wy8kS3elIplt/61GCd1x0LrgQjSkw3Tf2Rp0PU+EcqmcVfzGWp4W+4eOatDsibBLn1tSMAXbWI+PDQGvkfDrDZy9XWsLiK594cCzeio5QePjlt7QCjVm5K3UVoyWgWT0aajl3KVjne1o++fDRHxSahivsF1LAnT9Tpe7t4/lDVQoH3/9jAotP3AlhtmQE0qQjRJdt43QvILvqMsHNCdV4xD3ELROaVT2U5KCHp31OF/FZNQ7r7F5IlFZKXXkT0SCcq0vn7IMgBnuKWsCMzTm7/cAVSko7KRuZDifUi1voSS6LynKWWdgLSRzeRq1oah1+Xpr4nCb/5hP7sOd4DDBpWSgZG40VwBJKot2p4QgTN4dkqpReE1OB+REHObNKzkWmebSqH1GKCHKjEi8rWt7bpKew1nXz1wq+na0ud+9rA+feQm/7WDbFyd6wJCYfEPfIZsUGtZQAhln/l5ZE47yuCddE/5deC4Km/HquBoLPgUCJrLjy0TE5VAXjctEXxglXlzfBYOwLlOyMBH7uJxu7H4COLG3K0iqouIaJtvwdfLlTNjBeGn4tOwS1FcLXexe25TuPKBsqyoJhH4kjk60xjgNDIrEV8HAMiErenZ61hA8W1Q1T8=
    username: AgCmqAZoikdgEKn5rDTFMygjK3KIyTgqGjkP09QoFClB31B5hmMdiIYQoeec7oL0ZpX4VRNF51iaZh0r4QpuSLAF0Cb1s66u7hdD7dXmfAF7dulCIKCmE8DfchxUuSuic7M7ijD6PKbjp3T2SdZ1lsIhKgFKpTdC/VAYMrBZ8riFTBWZYE+8lp1fcszkLebq/6uxYX5/ovXPQs0MzeV8byGoULiDuvlyi0T0M1Nu+7a0aZwLr+ufoz7qUOlrsvzgH222ve5StftVupl6E72oo6jFw6XItAlbxHAo50u21pmEmcdq1EpFrh5ADGGzcQic9H3LvsE5rLtsTXZ/jZVEeE0hMUXaG2C6bQlSyrQlwEpDrnmLFf/hiS/wTjIVHEe0ciTDZNR+0jViLXP2o6AW6H6hWiF0/blmLa77guLCLulWDjU6F16GaxS/2T8OJ/o90+C3awQbbzok5cFD8pRyuBP6X/R8Xx0A39CyaE1CLrvOlyTNvFvJiqVAlPMF8gBcXw84J0B6c+HHo49flQXYS//TTXFXRdwMg1MANjd2CaPm+CtZnWQbjjxJaj0aMaY1QVIjTrktyD1O4bxt2QA6Sd78e+OY/rZpEJ5Fb6UzpvBIRfENCEEcEsgd2tTGjewWkBRVxvA3MxcU1sM5XBrVXVRKsPcZpYkec2I0BuT59grxYNQl7kom8tT/OufDY/SlvbEOVVjGkj7tnNLjEMOV
  template:
    metadata:
      name: insight-keycloak-admin
      namespace: insight
    type: Opaque
