CREATE DATABASE IF NOT EXISTS `bronze_salesforce`;

CREATE TABLE IF NOT EXISTS bronze_salesforce.Account
(
    `_airbyte_raw_id` String,
    `_airbyte_extracted_at` DateTime64(3),
    `_airbyte_meta` String,
    `_airbyte_generation_id` UInt32,
    `Id` Nullable(String),
    `IsDeleted` Nullable(Bool),
    `MasterRecordId` Nullable(String),
    `Name` Nullable(String),
    `Type` Nullable(String),
    `ParentId` Nullable(String),
    `BillingStreet` Nullable(String),
    `BillingCity` Nullable(String),
    `BillingState` Nullable(String),
    `BillingPostalCode` Nullable(String),
    `BillingCountry` Nullable(String),
    `BillingStateCode` Nullable(String),
    `BillingCountryCode` Nullable(String),
    `BillingLatitude` Nullable(Decimal(38, 9)),
    `BillingLongitude` Nullable(Decimal(38, 9)),
    `BillingGeocodeAccuracy` Nullable(String),
    `BillingAddress` Nullable(String),
    `ShippingStreet` Nullable(String),
    `ShippingCity` Nullable(String),
    `ShippingState` Nullable(String),
    `ShippingPostalCode` Nullable(String),
    `ShippingCountry` Nullable(String),
    `ShippingStateCode` Nullable(String),
    `ShippingCountryCode` Nullable(String),
    `ShippingLatitude` Nullable(Decimal(38, 9)),
    `ShippingLongitude` Nullable(Decimal(38, 9)),
    `ShippingGeocodeAccuracy` Nullable(String),
    `ShippingAddress` Nullable(String),
    `Phone` Nullable(String),
    `Fax` Nullable(String),
    `AccountNumber` Nullable(String),
    `Website` Nullable(String),
    `PhotoUrl` Nullable(String),
    `Sic` Nullable(String),
    `Industry` Nullable(String),
    `AnnualRevenue` Nullable(Decimal(38, 9)),
    `NumberOfEmployees` Nullable(Int64),
    `Ownership` Nullable(String),
    `TickerSymbol` Nullable(String),
    `Description` Nullable(String),
    `Rating` Nullable(String),
    `Site` Nullable(String),
    `OwnerId` Nullable(String),
    `CreatedDate` Nullable(DateTime64(3)),
    `CreatedById` Nullable(String),
    `LastModifiedDate` Nullable(DateTime64(3)),
    `LastModifiedById` Nullable(String),
    `SystemModstamp` Nullable(DateTime64(3)),
    `LastActivityDate` Nullable(Date32),
    `LastViewedDate` Nullable(DateTime64(3)),
    `LastReferencedDate` Nullable(DateTime64(3)),
    `Jigsaw` Nullable(String),
    `JigsawCompanyId` Nullable(String),
    `CleanStatus` Nullable(String),
    `AccountSource` Nullable(String),
    `DunsNumber` Nullable(String),
    `Tradestyle` Nullable(String),
    `NaicsCode` Nullable(String),
    `NaicsDesc` Nullable(String),
    `YearStarted` Nullable(String),
    `SicDesc` Nullable(String),
    `DandbCompanyId` Nullable(String),
    `OperatingHoursId` Nullable(String),
    `tenant_id` Nullable(String),
    `source_id` Nullable(String),
    `unique_key` Nullable(String),
    `data_source` Nullable(String),
    `collected_at` Nullable(DateTime64(3)),
    `custom_fields` Nullable(String)
)
ENGINE = ReplacingMergeTree(_airbyte_extracted_at)
ORDER BY unique_key
SETTINGS allow_nullable_key = 1, index_granularity = 8192
;

CREATE TABLE IF NOT EXISTS bronze_salesforce.Case
(
    `_airbyte_raw_id` String,
    `_airbyte_extracted_at` DateTime64(3),
    `_airbyte_meta` String,
    `_airbyte_generation_id` UInt32,
    `Id` Nullable(String),
    `IsDeleted` Nullable(Bool),
    `MasterRecordId` Nullable(String),
    `CaseNumber` Nullable(String),
    `ContactId` Nullable(String),
    `AccountId` Nullable(String),
    `AssetId` Nullable(String),
    `SourceId` Nullable(String),
    `ParentId` Nullable(String),
    `SuppliedName` Nullable(String),
    `SuppliedEmail` Nullable(String),
    `SuppliedPhone` Nullable(String),
    `SuppliedCompany` Nullable(String),
    `Type` Nullable(String),
    `Status` Nullable(String),
    `Reason` Nullable(String),
    `Origin` Nullable(String),
    `Subject` Nullable(String),
    `Priority` Nullable(String),
    `Description` Nullable(String),
    `IsClosed` Nullable(Bool),
    `ClosedDate` Nullable(DateTime64(3)),
    `IsEscalated` Nullable(Bool),
    `OwnerId` Nullable(String),
    `CreatedDate` Nullable(DateTime64(3)),
    `CreatedById` Nullable(String),
    `LastModifiedDate` Nullable(DateTime64(3)),
    `LastModifiedById` Nullable(String),
    `SystemModstamp` Nullable(DateTime64(3)),
    `ContactPhone` Nullable(String),
    `ContactMobile` Nullable(String),
    `ContactEmail` Nullable(String),
    `ContactFax` Nullable(String),
    `Comments` Nullable(String),
    `LastViewedDate` Nullable(DateTime64(3)),
    `LastReferencedDate` Nullable(DateTime64(3)),
    `tenant_id` Nullable(String),
    `source_id` Nullable(String),
    `unique_key` Nullable(String),
    `data_source` Nullable(String),
    `collected_at` Nullable(DateTime64(3)),
    `custom_fields` Nullable(String)
)
ENGINE = ReplacingMergeTree(_airbyte_extracted_at)
ORDER BY unique_key
SETTINGS allow_nullable_key = 1, index_granularity = 8192
;

CREATE TABLE IF NOT EXISTS bronze_salesforce.Contact
(
    `_airbyte_raw_id` String,
    `_airbyte_extracted_at` DateTime64(3),
    `_airbyte_meta` String,
    `_airbyte_generation_id` UInt32,
    `Id` Nullable(String),
    `IsDeleted` Nullable(Bool),
    `MasterRecordId` Nullable(String),
    `AccountId` Nullable(String),
    `LastName` Nullable(String),
    `FirstName` Nullable(String),
    `Salutation` Nullable(String),
    `Name` Nullable(String),
    `OtherStreet` Nullable(String),
    `OtherCity` Nullable(String),
    `OtherState` Nullable(String),
    `OtherPostalCode` Nullable(String),
    `OtherCountry` Nullable(String),
    `OtherStateCode` Nullable(String),
    `OtherCountryCode` Nullable(String),
    `OtherLatitude` Nullable(Decimal(38, 9)),
    `OtherLongitude` Nullable(Decimal(38, 9)),
    `OtherGeocodeAccuracy` Nullable(String),
    `OtherAddress` Nullable(String),
    `MailingStreet` Nullable(String),
    `MailingCity` Nullable(String),
    `MailingState` Nullable(String),
    `MailingPostalCode` Nullable(String),
    `MailingCountry` Nullable(String),
    `MailingStateCode` Nullable(String),
    `MailingCountryCode` Nullable(String),
    `MailingLatitude` Nullable(Decimal(38, 9)),
    `MailingLongitude` Nullable(Decimal(38, 9)),
    `MailingGeocodeAccuracy` Nullable(String),
    `MailingAddress` Nullable(String),
    `Phone` Nullable(String),
    `Fax` Nullable(String),
    `MobilePhone` Nullable(String),
    `HomePhone` Nullable(String),
    `OtherPhone` Nullable(String),
    `AssistantPhone` Nullable(String),
    `ReportsToId` Nullable(String),
    `Email` Nullable(String),
    `Title` Nullable(String),
    `Department` Nullable(String),
    `AssistantName` Nullable(String),
    `LeadSource` Nullable(String),
    `Birthdate` Nullable(Date32),
    `Description` Nullable(String),
    `OwnerId` Nullable(String),
    `CreatedDate` Nullable(DateTime64(3)),
    `CreatedById` Nullable(String),
    `LastModifiedDate` Nullable(DateTime64(3)),
    `LastModifiedById` Nullable(String),
    `SystemModstamp` Nullable(DateTime64(3)),
    `LastActivityDate` Nullable(Date32),
    `LastCURequestDate` Nullable(DateTime64(3)),
    `LastCUUpdateDate` Nullable(DateTime64(3)),
    `LastViewedDate` Nullable(DateTime64(3)),
    `LastReferencedDate` Nullable(DateTime64(3)),
    `EmailBouncedReason` Nullable(String),
    `EmailBouncedDate` Nullable(DateTime64(3)),
    `IsEmailBounced` Nullable(Bool),
    `PhotoUrl` Nullable(String),
    `Jigsaw` Nullable(String),
    `JigsawContactId` Nullable(String),
    `CleanStatus` Nullable(String),
    `IndividualId` Nullable(String),
    `IsPriorityRecord` Nullable(Bool),
    `ContactSource` Nullable(String),
    `tenant_id` Nullable(String),
    `source_id` Nullable(String),
    `unique_key` Nullable(String),
    `data_source` Nullable(String),
    `collected_at` Nullable(DateTime64(3)),
    `custom_fields` Nullable(String)
)
ENGINE = ReplacingMergeTree(_airbyte_extracted_at)
ORDER BY unique_key
SETTINGS allow_nullable_key = 1, index_granularity = 8192
;

CREATE TABLE IF NOT EXISTS bronze_salesforce.Event
(
    `_airbyte_raw_id` String,
    `_airbyte_extracted_at` DateTime64(3),
    `_airbyte_meta` String,
    `_airbyte_generation_id` UInt32,
    `Id` Nullable(String),
    `WhoId` Nullable(String),
    `WhatId` Nullable(String),
    `Subject` Nullable(String),
    `Location` Nullable(String),
    `IsAllDayEvent` Nullable(Bool),
    `ActivityDateTime` Nullable(DateTime64(3)),
    `ActivityDate` Nullable(Date32),
    `DurationInMinutes` Nullable(Int64),
    `StartDateTime` Nullable(DateTime64(3)),
    `EndDateTime` Nullable(DateTime64(3)),
    `EndDate` Nullable(Date32),
    `Description` Nullable(String),
    `AccountId` Nullable(String),
    `OwnerId` Nullable(String),
    `IsPrivate` Nullable(Bool),
    `ShowAs` Nullable(String),
    `IsDeleted` Nullable(Bool),
    `IsChild` Nullable(Bool),
    `IsGroupEvent` Nullable(Bool),
    `GroupEventType` Nullable(String),
    `CreatedDate` Nullable(DateTime64(3)),
    `CreatedById` Nullable(String),
    `LastModifiedDate` Nullable(DateTime64(3)),
    `LastModifiedById` Nullable(String),
    `SystemModstamp` Nullable(DateTime64(3)),
    `IsArchived` Nullable(Bool),
    `RecurrenceActivityId` Nullable(String),
    `IsRecurrence` Nullable(Bool),
    `RecurrenceStartDateTime` Nullable(DateTime64(3)),
    `RecurrenceEndDateOnly` Nullable(Date32),
    `RecurrenceTimeZoneSidKey` Nullable(String),
    `RecurrenceType` Nullable(String),
    `RecurrenceInterval` Nullable(Int64),
    `RecurrenceDayOfWeekMask` Nullable(Int64),
    `RecurrenceDayOfMonth` Nullable(Int64),
    `RecurrenceInstance` Nullable(String),
    `RecurrenceMonthOfYear` Nullable(String),
    `ReminderDateTime` Nullable(DateTime64(3)),
    `IsReminderSet` Nullable(Bool),
    `EventSubtype` Nullable(String),
    `IsRecurrence2Exclusion` Nullable(Bool),
    `Recurrence2PatternText` Nullable(String),
    `Recurrence2PatternVersion` Nullable(String),
    `IsRecurrence2` Nullable(Bool),
    `IsRecurrence2Exception` Nullable(Bool),
    `Recurrence2PatternStartDate` Nullable(DateTime64(3)),
    `Recurrence2PatternTimeZone` Nullable(String),
    `ServiceAppointmentId` Nullable(String),
    `tenant_id` Nullable(String),
    `source_id` Nullable(String),
    `unique_key` Nullable(String),
    `data_source` Nullable(String),
    `collected_at` Nullable(DateTime64(3)),
    `custom_fields` Nullable(String)
)
ENGINE = ReplacingMergeTree(_airbyte_extracted_at)
ORDER BY unique_key
SETTINGS allow_nullable_key = 1, index_granularity = 8192
;

CREATE TABLE IF NOT EXISTS bronze_salesforce.Lead
(
    `_airbyte_raw_id` String,
    `_airbyte_extracted_at` DateTime64(3),
    `_airbyte_meta` String,
    `_airbyte_generation_id` UInt32,
    `Id` Nullable(String),
    `IsDeleted` Nullable(Bool),
    `MasterRecordId` Nullable(String),
    `LastName` Nullable(String),
    `FirstName` Nullable(String),
    `Salutation` Nullable(String),
    `Name` Nullable(String),
    `Title` Nullable(String),
    `Company` Nullable(String),
    `Street` Nullable(String),
    `City` Nullable(String),
    `State` Nullable(String),
    `PostalCode` Nullable(String),
    `Country` Nullable(String),
    `StateCode` Nullable(String),
    `CountryCode` Nullable(String),
    `Latitude` Nullable(Decimal(38, 9)),
    `Longitude` Nullable(Decimal(38, 9)),
    `GeocodeAccuracy` Nullable(String),
    `Address` Nullable(String),
    `Phone` Nullable(String),
    `MobilePhone` Nullable(String),
    `Fax` Nullable(String),
    `Email` Nullable(String),
    `Website` Nullable(String),
    `PhotoUrl` Nullable(String),
    `Description` Nullable(String),
    `LeadSource` Nullable(String),
    `Status` Nullable(String),
    `Industry` Nullable(String),
    `Rating` Nullable(String),
    `AnnualRevenue` Nullable(Decimal(38, 9)),
    `NumberOfEmployees` Nullable(Int64),
    `OwnerId` Nullable(String),
    `IsConverted` Nullable(Bool),
    `ConvertedDate` Nullable(Date32),
    `ConvertedAccountId` Nullable(String),
    `ConvertedContactId` Nullable(String),
    `ConvertedOpportunityId` Nullable(String),
    `IsUnreadByOwner` Nullable(Bool),
    `CreatedDate` Nullable(DateTime64(3)),
    `CreatedById` Nullable(String),
    `LastModifiedDate` Nullable(DateTime64(3)),
    `LastModifiedById` Nullable(String),
    `SystemModstamp` Nullable(DateTime64(3)),
    `LastActivityDate` Nullable(Date32),
    `LastViewedDate` Nullable(DateTime64(3)),
    `LastReferencedDate` Nullable(DateTime64(3)),
    `Jigsaw` Nullable(String),
    `JigsawContactId` Nullable(String),
    `CleanStatus` Nullable(String),
    `CompanyDunsNumber` Nullable(String),
    `DandbCompanyId` Nullable(String),
    `EmailBouncedReason` Nullable(String),
    `EmailBouncedDate` Nullable(DateTime64(3)),
    `IndividualId` Nullable(String),
    `IsPriorityRecord` Nullable(Bool),
    `tenant_id` Nullable(String),
    `source_id` Nullable(String),
    `unique_key` Nullable(String),
    `data_source` Nullable(String),
    `collected_at` Nullable(DateTime64(3)),
    `custom_fields` Nullable(String)
)
ENGINE = ReplacingMergeTree(_airbyte_extracted_at)
ORDER BY unique_key
SETTINGS allow_nullable_key = 1, index_granularity = 8192
;

CREATE TABLE IF NOT EXISTS bronze_salesforce.Opportunity
(
    `_airbyte_raw_id` String,
    `_airbyte_extracted_at` DateTime64(3),
    `_airbyte_meta` String,
    `_airbyte_generation_id` UInt32,
    `Id` Nullable(String),
    `IsDeleted` Nullable(Bool),
    `AccountId` Nullable(String),
    `IsPrivate` Nullable(Bool),
    `Name` Nullable(String),
    `Description` Nullable(String),
    `StageName` Nullable(String),
    `Amount` Nullable(Decimal(38, 9)),
    `Probability` Nullable(Decimal(38, 9)),
    `ExpectedRevenue` Nullable(Decimal(38, 9)),
    `TotalOpportunityQuantity` Nullable(Decimal(38, 9)),
    `CloseDate` Nullable(Date32),
    `Type` Nullable(String),
    `NextStep` Nullable(String),
    `LeadSource` Nullable(String),
    `IsClosed` Nullable(Bool),
    `IsWon` Nullable(Bool),
    `ForecastCategory` Nullable(String),
    `ForecastCategoryName` Nullable(String),
    `CampaignId` Nullable(String),
    `HasOpportunityLineItem` Nullable(Bool),
    `Pricebook2Id` Nullable(String),
    `OwnerId` Nullable(String),
    `CreatedDate` Nullable(DateTime64(3)),
    `CreatedById` Nullable(String),
    `LastModifiedDate` Nullable(DateTime64(3)),
    `LastModifiedById` Nullable(String),
    `SystemModstamp` Nullable(DateTime64(3)),
    `LastActivityDate` Nullable(Date32),
    `PushCount` Nullable(Int64),
    `LastStageChangeDate` Nullable(DateTime64(3)),
    `FiscalQuarter` Nullable(Int64),
    `FiscalYear` Nullable(Int64),
    `Fiscal` Nullable(String),
    `ContactId` Nullable(String),
    `LastViewedDate` Nullable(DateTime64(3)),
    `LastReferencedDate` Nullable(DateTime64(3)),
    `HasOpenActivity` Nullable(Bool),
    `HasOverdueTask` Nullable(Bool),
    `LastAmountChangedHistoryId` Nullable(String),
    `LastCloseDateChangedHistoryId` Nullable(String),
    `tenant_id` Nullable(String),
    `source_id` Nullable(String),
    `unique_key` Nullable(String),
    `data_source` Nullable(String),
    `collected_at` Nullable(DateTime64(3)),
    `custom_fields` Nullable(String)
)
ENGINE = ReplacingMergeTree(_airbyte_extracted_at)
ORDER BY unique_key
SETTINGS allow_nullable_key = 1, index_granularity = 8192
;

CREATE TABLE IF NOT EXISTS bronze_salesforce.OpportunityContactRole
(
    `_airbyte_raw_id` String,
    `_airbyte_extracted_at` DateTime64(3),
    `_airbyte_meta` String,
    `_airbyte_generation_id` UInt32,
    `Id` Nullable(String),
    `OpportunityId` Nullable(String),
    `ContactId` Nullable(String),
    `Role` Nullable(String),
    `IsPrimary` Nullable(Bool),
    `CreatedDate` Nullable(DateTime64(3)),
    `CreatedById` Nullable(String),
    `LastModifiedDate` Nullable(DateTime64(3)),
    `LastModifiedById` Nullable(String),
    `SystemModstamp` Nullable(DateTime64(3)),
    `IsDeleted` Nullable(Bool),
    `tenant_id` Nullable(String),
    `source_id` Nullable(String),
    `unique_key` Nullable(String),
    `data_source` Nullable(String),
    `collected_at` Nullable(DateTime64(3)),
    `custom_fields` Nullable(String)
)
ENGINE = ReplacingMergeTree(_airbyte_extracted_at)
ORDER BY unique_key
SETTINGS allow_nullable_key = 1, index_granularity = 8192
;

CREATE TABLE IF NOT EXISTS bronze_salesforce.OpportunityHistory
(
    `_airbyte_raw_id` String,
    `_airbyte_extracted_at` DateTime64(3),
    `_airbyte_meta` String,
    `_airbyte_generation_id` UInt32,
    `Id` Nullable(String),
    `OpportunityId` Nullable(String),
    `CreatedById` Nullable(String),
    `CreatedDate` Nullable(DateTime64(3)),
    `StageName` Nullable(String),
    `Amount` Nullable(Decimal(38, 9)),
    `ExpectedRevenue` Nullable(Decimal(38, 9)),
    `CloseDate` Nullable(Date32),
    `Probability` Nullable(Decimal(38, 9)),
    `ForecastCategory` Nullable(String),
    `SystemModstamp` Nullable(DateTime64(3)),
    `IsDeleted` Nullable(Bool),
    `PrevAmount` Nullable(Decimal(38, 9)),
    `PrevCloseDate` Nullable(Date32),
    `tenant_id` Nullable(String),
    `source_id` Nullable(String),
    `unique_key` Nullable(String),
    `data_source` Nullable(String),
    `collected_at` Nullable(DateTime64(3)),
    `custom_fields` Nullable(String)
)
ENGINE = ReplacingMergeTree(_airbyte_extracted_at)
ORDER BY unique_key
SETTINGS allow_nullable_key = 1, index_granularity = 8192
;

CREATE TABLE IF NOT EXISTS bronze_salesforce.Task
(
    `_airbyte_raw_id` String,
    `_airbyte_extracted_at` DateTime64(3),
    `_airbyte_meta` String,
    `_airbyte_generation_id` UInt32,
    `Id` Nullable(String),
    `WhoId` Nullable(String),
    `WhatId` Nullable(String),
    `Subject` Nullable(String),
    `ActivityDate` Nullable(Date32),
    `Status` Nullable(String),
    `Priority` Nullable(String),
    `IsHighPriority` Nullable(Bool),
    `OwnerId` Nullable(String),
    `Description` Nullable(String),
    `IsDeleted` Nullable(Bool),
    `AccountId` Nullable(String),
    `IsClosed` Nullable(Bool),
    `CreatedDate` Nullable(DateTime64(3)),
    `CreatedById` Nullable(String),
    `LastModifiedDate` Nullable(DateTime64(3)),
    `LastModifiedById` Nullable(String),
    `SystemModstamp` Nullable(DateTime64(3)),
    `IsArchived` Nullable(Bool),
    `CallDurationInSeconds` Nullable(Int64),
    `CallType` Nullable(String),
    `CallDisposition` Nullable(String),
    `CallObject` Nullable(String),
    `ReminderDateTime` Nullable(DateTime64(3)),
    `IsReminderSet` Nullable(Bool),
    `RecurrenceActivityId` Nullable(String),
    `IsRecurrence` Nullable(Bool),
    `RecurrenceStartDateOnly` Nullable(Date32),
    `RecurrenceEndDateOnly` Nullable(Date32),
    `RecurrenceTimeZoneSidKey` Nullable(String),
    `RecurrenceType` Nullable(String),
    `RecurrenceInterval` Nullable(Int64),
    `RecurrenceDayOfWeekMask` Nullable(Int64),
    `RecurrenceDayOfMonth` Nullable(Int64),
    `RecurrenceInstance` Nullable(String),
    `RecurrenceMonthOfYear` Nullable(String),
    `RecurrenceRegeneratedType` Nullable(String),
    `TaskSubtype` Nullable(String),
    `CompletedDateTime` Nullable(DateTime64(3)),
    `tenant_id` Nullable(String),
    `source_id` Nullable(String),
    `unique_key` Nullable(String),
    `data_source` Nullable(String),
    `collected_at` Nullable(DateTime64(3)),
    `custom_fields` Nullable(String)
)
ENGINE = ReplacingMergeTree(_airbyte_extracted_at)
ORDER BY unique_key
SETTINGS allow_nullable_key = 1, index_granularity = 8192
;

CREATE TABLE IF NOT EXISTS bronze_salesforce.User
(
    `_airbyte_raw_id` String,
    `_airbyte_extracted_at` DateTime64(3),
    `_airbyte_meta` String,
    `_airbyte_generation_id` UInt32,
    `Id` Nullable(String),
    `Username` Nullable(String),
    `LastName` Nullable(String),
    `FirstName` Nullable(String),
    `Name` Nullable(String),
    `CompanyName` Nullable(String),
    `Division` Nullable(String),
    `Department` Nullable(String),
    `Title` Nullable(String),
    `Street` Nullable(String),
    `City` Nullable(String),
    `State` Nullable(String),
    `PostalCode` Nullable(String),
    `Country` Nullable(String),
    `StateCode` Nullable(String),
    `CountryCode` Nullable(String),
    `Latitude` Nullable(Decimal(38, 9)),
    `Longitude` Nullable(Decimal(38, 9)),
    `GeocodeAccuracy` Nullable(String),
    `Address` Nullable(String),
    `Email` Nullable(String),
    `EmailPreferencesAutoBcc` Nullable(Bool),
    `EmailPreferencesAutoBccStayInTouch` Nullable(Bool),
    `EmailPreferencesStayInTouchReminder` Nullable(Bool),
    `SenderEmail` Nullable(String),
    `SenderName` Nullable(String),
    `Signature` Nullable(String),
    `StayInTouchSubject` Nullable(String),
    `StayInTouchSignature` Nullable(String),
    `StayInTouchNote` Nullable(String),
    `Phone` Nullable(String),
    `Fax` Nullable(String),
    `MobilePhone` Nullable(String),
    `Alias` Nullable(String),
    `CommunityNickname` Nullable(String),
    `BadgeText` Nullable(String),
    `IsActive` Nullable(Bool),
    `TimeZoneSidKey` Nullable(String),
    `UserRoleId` Nullable(String),
    `LocaleSidKey` Nullable(String),
    `ReceivesInfoEmails` Nullable(Bool),
    `ReceivesAdminInfoEmails` Nullable(Bool),
    `EmailEncodingKey` Nullable(String),
    `ProfileId` Nullable(String),
    `UserType` Nullable(String),
    `StartDay` Nullable(String),
    `EndDay` Nullable(String),
    `LanguageLocaleKey` Nullable(String),
    `EmployeeNumber` Nullable(String),
    `DelegatedApproverId` Nullable(String),
    `ManagerId` Nullable(String),
    `LastLoginDate` Nullable(DateTime64(3)),
    `LastPasswordChangeDate` Nullable(DateTime64(3)),
    `CreatedDate` Nullable(DateTime64(3)),
    `CreatedById` Nullable(String),
    `LastModifiedDate` Nullable(DateTime64(3)),
    `LastModifiedById` Nullable(String),
    `SystemModstamp` Nullable(DateTime64(3)),
    `PasswordExpirationDate` Nullable(DateTime64(3)),
    `NumberOfFailedLogins` Nullable(Int64),
    `SuAccessExpirationDate` Nullable(Date32),
    `OfflineTrialExpirationDate` Nullable(DateTime64(3)),
    `OfflinePdaTrialExpirationDate` Nullable(DateTime64(3)),
    `UserPermissionsMarketingUser` Nullable(Bool),
    `UserPermissionsOfflineUser` Nullable(Bool),
    `UserPermissionsCallCenterAutoLogin` Nullable(Bool),
    `UserPermissionsSFContentUser` Nullable(Bool),
    `UserPermissionsKnowledgeUser` Nullable(Bool),
    `UserPermissionsInteractionUser` Nullable(Bool),
    `UserPermissionsSupportUser` Nullable(Bool),
    `UserPermissionsJigsawProspectingUser` Nullable(Bool),
    `UserPermissionsSiteforceContributorUser` Nullable(Bool),
    `UserPermissionsSiteforcePublisherUser` Nullable(Bool),
    `UserPermissionsWorkDotComUserFeature` Nullable(Bool),
    `ForecastEnabled` Nullable(Bool),
    `UserPreferencesActivityRemindersPopup` Nullable(Bool),
    `UserPreferencesEventRemindersCheckboxDefault` Nullable(Bool),
    `UserPreferencesTaskRemindersCheckboxDefault` Nullable(Bool),
    `UserPreferencesReminderSoundOff` Nullable(Bool),
    `UserPreferencesDisableAllFeedsEmail` Nullable(Bool),
    `UserPreferencesDisableFollowersEmail` Nullable(Bool),
    `UserPreferencesDisableProfilePostEmail` Nullable(Bool),
    `UserPreferencesDisableChangeCommentEmail` Nullable(Bool),
    `UserPreferencesDisableLaterCommentEmail` Nullable(Bool),
    `UserPreferencesDisProfPostCommentEmail` Nullable(Bool),
    `UserPreferencesContentNoEmail` Nullable(Bool),
    `UserPreferencesContentEmailAsAndWhen` Nullable(Bool),
    `UserPreferencesApexPagesDeveloperMode` Nullable(Bool),
    `UserPreferencesReceiveNoNotificationsAsApprover` Nullable(Bool),
    `UserPreferencesReceiveNotificationsAsDelegatedApprover` Nullable(Bool),
    `UserPreferencesHideCSNGetChatterMobileTask` Nullable(Bool),
    `UserPreferencesDisableMentionsPostEmail` Nullable(Bool),
    `UserPreferencesDisMentionsCommentEmail` Nullable(Bool),
    `UserPreferencesHideCSNDesktopTask` Nullable(Bool),
    `UserPreferencesHideChatterOnboardingSplash` Nullable(Bool),
    `UserPreferencesHideSecondChatterOnboardingSplash` Nullable(Bool),
    `UserPreferencesDisCommentAfterLikeEmail` Nullable(Bool),
    `UserPreferencesDisableLikeEmail` Nullable(Bool),
    `UserPreferencesSortFeedByComment` Nullable(Bool),
    `UserPreferencesDisableMessageEmail` Nullable(Bool),
    `UserPreferencesJigsawListUser` Nullable(Bool),
    `UserPreferencesDisableBookmarkEmail` Nullable(Bool),
    `UserPreferencesDisableSharePostEmail` Nullable(Bool),
    `UserPreferencesActionLauncherEinsteinGptConsent` Nullable(Bool),
    `UserPreferencesAssistiveActionsEnabledInActionLauncher` Nullable(Bool),
    `UserPreferencesEnableAutoSubForFeeds` Nullable(Bool),
    `UserPreferencesDisableFileShareNotificationsForApi` Nullable(Bool),
    `UserPreferencesShowTitleToExternalUsers` Nullable(Bool),
    `UserPreferencesShowManagerToExternalUsers` Nullable(Bool),
    `UserPreferencesShowEmailToExternalUsers` Nullable(Bool),
    `UserPreferencesShowWorkPhoneToExternalUsers` Nullable(Bool),
    `UserPreferencesShowMobilePhoneToExternalUsers` Nullable(Bool),
    `UserPreferencesShowFaxToExternalUsers` Nullable(Bool),
    `UserPreferencesShowStreetAddressToExternalUsers` Nullable(Bool),
    `UserPreferencesShowCityToExternalUsers` Nullable(Bool),
    `UserPreferencesShowStateToExternalUsers` Nullable(Bool),
    `UserPreferencesShowPostalCodeToExternalUsers` Nullable(Bool),
    `UserPreferencesShowCountryToExternalUsers` Nullable(Bool),
    `UserPreferencesShowProfilePicToGuestUsers` Nullable(Bool),
    `UserPreferencesShowTitleToGuestUsers` Nullable(Bool),
    `UserPreferencesShowCityToGuestUsers` Nullable(Bool),
    `UserPreferencesShowStateToGuestUsers` Nullable(Bool),
    `UserPreferencesShowPostalCodeToGuestUsers` Nullable(Bool),
    `UserPreferencesShowCountryToGuestUsers` Nullable(Bool),
    `UserPreferencesShowForecastingChangeSignals` Nullable(Bool),
    `UserPreferencesLiveAgentMiawSetupDeflection` Nullable(Bool),
    `UserPreferencesHideS1BrowserUI` Nullable(Bool),
    `UserPreferencesDisableEndorsementEmail` Nullable(Bool),
    `UserPreferencesPathAssistantCollapsed` Nullable(Bool),
    `UserPreferencesCacheDiagnostics` Nullable(Bool),
    `UserPreferencesShowEmailToGuestUsers` Nullable(Bool),
    `UserPreferencesShowManagerToGuestUsers` Nullable(Bool),
    `UserPreferencesShowWorkPhoneToGuestUsers` Nullable(Bool),
    `UserPreferencesShowMobilePhoneToGuestUsers` Nullable(Bool),
    `UserPreferencesShowFaxToGuestUsers` Nullable(Bool),
    `UserPreferencesShowStreetAddressToGuestUsers` Nullable(Bool),
    `UserPreferencesLightningExperiencePreferred` Nullable(Bool),
    `UserPreferencesPreviewLightning` Nullable(Bool),
    `UserPreferencesHideEndUserOnboardingAssistantModal` Nullable(Bool),
    `UserPreferencesHideLightningMigrationModal` Nullable(Bool),
    `UserPreferencesHideSfxWelcomeMat` Nullable(Bool),
    `UserPreferencesHideBiggerPhotoCallout` Nullable(Bool),
    `UserPreferencesGlobalNavBarWTShown` Nullable(Bool),
    `UserPreferencesGlobalNavGridMenuWTShown` Nullable(Bool),
    `UserPreferencesCreateLEXAppsWTShown` Nullable(Bool),
    `UserPreferencesFavoritesWTShown` Nullable(Bool),
    `UserPreferencesRecordHomeSectionCollapseWTShown` Nullable(Bool),
    `UserPreferencesRecordHomeReservedWTShown` Nullable(Bool),
    `UserPreferencesFavoritesShowTopFavorites` Nullable(Bool),
    `UserPreferencesExcludeMailAppAttachments` Nullable(Bool),
    `UserPreferencesSuppressTaskSFXReminders` Nullable(Bool),
    `UserPreferencesSuppressEventSFXReminders` Nullable(Bool),
    `UserPreferencesPreviewCustomTheme` Nullable(Bool),
    `UserPreferencesHasCelebrationBadge` Nullable(Bool),
    `UserPreferencesUserDebugModePref` Nullable(Bool),
    `UserPreferencesSRHOverrideActivities` Nullable(Bool),
    `UserPreferencesNewLightningReportRunPageEnabled` Nullable(Bool),
    `UserPreferencesReverseOpenActivitiesView` Nullable(Bool),
    `UserPreferencesShowTerritoryTimeZoneShifts` Nullable(Bool),
    `UserPreferencesHasSentWarningEmail` Nullable(Bool),
    `UserPreferencesHasSentWarningEmail238` Nullable(Bool),
    `UserPreferencesHasSentWarningEmail240` Nullable(Bool),
    `UserPreferencesNativeEmailClient` Nullable(Bool),
    `UserPreferencesShowForecastingRoundedAmounts` Nullable(Bool),
    `ContactId` Nullable(String),
    `AccountId` Nullable(String),
    `CallCenterId` Nullable(String),
    `Extension` Nullable(String),
    `FederationIdentifier` Nullable(String),
    `AboutMe` Nullable(String),
    `FullPhotoUrl` Nullable(String),
    `SmallPhotoUrl` Nullable(String),
    `IsExtIndicatorVisible` Nullable(Bool),
    `OutOfOfficeMessage` Nullable(String),
    `MediumPhotoUrl` Nullable(String),
    `DigestFrequency` Nullable(String),
    `DefaultGroupNotificationFrequency` Nullable(String),
    `JigsawImportLimitOverride` Nullable(Int64),
    `LastViewedDate` Nullable(DateTime64(3)),
    `LastReferencedDate` Nullable(DateTime64(3)),
    `BannerPhotoUrl` Nullable(String),
    `SmallBannerPhotoUrl` Nullable(String),
    `MediumBannerPhotoUrl` Nullable(String),
    `IsProfilePhotoActive` Nullable(Bool),
    `IndividualId` Nullable(String),
    `tenant_id` Nullable(String),
    `source_id` Nullable(String),
    `unique_key` Nullable(String),
    `data_source` Nullable(String),
    `collected_at` Nullable(DateTime64(3)),
    `custom_fields` Nullable(String)
)
ENGINE = ReplacingMergeTree(_airbyte_extracted_at)
ORDER BY unique_key
SETTINGS allow_nullable_key = 1, index_granularity = 8192
;

