apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-auth
  namespace: redis
spec:
  encryptedData:
    password: AgAb+TvLKK/QYsZp/RFamXATzPz/+9ZrWRHyPMnfWHR6Oi/QJVV7G5gGcMmNthV6zAbkvi6PA+bSBL+wF3DTPFwUtUCgH/D+fo7+20yIZXZKZVKBrOgTktZq2981U43xJnuv5/JMLsaUaquYVmWyAboPa1CnILia7akXQvaCHrQ0oV13o+YSffL04aMWnkNSkXwwDSuCvxMrZgYbYzf9/3ehAR/jo6ZJqvaE1uCexhhT+UewBE7/x13QLclJHwguPiEeWtKyBSl1hLr0oqSEzOzx/GVi8CvXm6hT4ubVzBBwZK6tRR6qFYvSiWfztHSMzbDMgmavBmUf9Gt3WlgBkYa9XVEbDyO/nQEYEvpmvQi2JdNTp544xlu4J/RlLyr/YO53cocOPTUTeYthkHRYzFrrwUduZ/m4Dpi4GdBWbV3DpYNUMSHnYw1WVN2oxhf48JvQD4ljavgw5FhSg7SZVYVFJRBNlcesl5aNuvkxJeuv39c8DtQtdGP19pnqHNmqhDvJoouVzCFUR3pb3NyOhZgWsDBF0WM0d97oJSUPWEOorHwVphwh2+tZ0eCyRowiGCjCqU0QFIQG2szm8r/Cn7JFY1ITcQidMB2Fxxh0s/rBn06IVLoZljIWXhmXAqn/9SawBn42ZvnidpZLdnUx7tPzPru5tDgwiX8kpxncKwQlaF+iO4sn79WgMje85SDL41hjjygw1qG+9wFxztHsH9QcQlbSJQoNzFkudQUhfcO/J8GHbCwBvP4F/JlKBBcihrU=
  template:
    metadata:
      name: redis-auth
      namespace: redis
    type: Opaque
