/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as IcPersonRouteImport } from './routes/ic.$person'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as PortalCustomRouteImport } from './routes/portal.custom'
import { Route as IcPersonIndexRouteImport } from './routes/ic.$person.index'
import { Route as IcPersonPersonalRouteImport } from './routes/ic.$person.personal'
import { Route as IcPersonTeamRouteImport } from './routes/ic.$person.team'
import { Route as PortalCustomIndexRouteImport } from './routes/portal.custom.index'
import { Route as PortalCustomNameRouteImport } from './routes/portal.custom.$name'
import { Route as PortalCustomAlertsIndexRouteImport } from './routes/portal.custom.alerts.index'
import { Route as PortalCustomAlertsNewRouteImport } from './routes/portal.custom.alerts.new'
import { Route as PortalCustomDatasetsIndexRouteImport } from './routes/portal.custom.datasets.index'
import { Route as PortalCustomDatasetsNameRouteImport } from './routes/portal.custom.datasets.$name'
import { Route as PortalCustomMetricsIndexRouteImport } from './routes/portal.custom.metrics.index'
import { Route as PortalCustomMetricsNameRouteImport } from './routes/portal.custom.metrics.$name'
import { Route as PortalCustomNewKindRouteImport } from './routes/portal.custom.new.$kind'
import { Route as PortalCustomWidgetsIndexRouteImport } from './routes/portal.custom.widgets.index'
import { Route as PortalCustomWidgetsNameRouteImport } from './routes/portal.custom.widgets.$name'
import { Route as PortalCustomAlertsIdIndexRouteImport } from './routes/portal.custom.alerts.$id.index'
import { Route as PortalCustomAlertsIdEditRouteImport } from './routes/portal.custom.alerts.$id.edit'
import { Route as PortalCustomEditKindNameRouteImport } from './routes/portal.custom.edit.$kind.$name'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const IcPersonRoute = IcPersonRouteImport.update({
  id: '/ic/$person',
  path: '/ic/$person',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalCustomRoute = PortalCustomRouteImport.update({
  id: '/custom',
  path: '/custom',
  getParentRoute: () => PortalRoute,
} as any)
const IcPersonIndexRoute = IcPersonIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IcPersonRoute,
} as any)
const IcPersonPersonalRoute = IcPersonPersonalRouteImport.update({
  id: '/personal',
  path: '/personal',
  getParentRoute: () => IcPersonRoute,
} as any)
const IcPersonTeamRoute = IcPersonTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => IcPersonRoute,
} as any)
const PortalCustomIndexRoute = PortalCustomIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalCustomRoute,
} as any)
const PortalCustomNameRoute = PortalCustomNameRouteImport.update({
  id: '/$name',
  path: '/$name',
  getParentRoute: () => PortalCustomRoute,
} as any)
const PortalCustomAlertsIndexRoute = PortalCustomAlertsIndexRouteImport.update({
  id: '/alerts/',
  path: '/alerts/',
  getParentRoute: () => PortalCustomRoute,
} as any)
const PortalCustomAlertsNewRoute = PortalCustomAlertsNewRouteImport.update({
  id: '/alerts/new',
  path: '/alerts/new',
  getParentRoute: () => PortalCustomRoute,
} as any)
const PortalCustomDatasetsIndexRoute =
  PortalCustomDatasetsIndexRouteImport.update({
    id: '/datasets/',
    path: '/datasets/',
    getParentRoute: () => PortalCustomRoute,
  } as any)
const PortalCustomDatasetsNameRoute =
  PortalCustomDatasetsNameRouteImport.update({
    id: '/datasets/$name',
    path: '/datasets/$name',
    getParentRoute: () => PortalCustomRoute,
  } as any)
const PortalCustomMetricsIndexRoute =
  PortalCustomMetricsIndexRouteImport.update({
    id: '/metrics/',
    path: '/metrics/',
    getParentRoute: () => PortalCustomRoute,
  } as any)
const PortalCustomMetricsNameRoute = PortalCustomMetricsNameRouteImport.update({
  id: '/metrics/$name',
  path: '/metrics/$name',
  getParentRoute: () => PortalCustomRoute,
} as any)
const PortalCustomNewKindRoute = PortalCustomNewKindRouteImport.update({
  id: '/new/$kind',
  path: '/new/$kind',
  getParentRoute: () => PortalCustomRoute,
} as any)
const PortalCustomWidgetsIndexRoute =
  PortalCustomWidgetsIndexRouteImport.update({
    id: '/widgets/',
    path: '/widgets/',
    getParentRoute: () => PortalCustomRoute,
  } as any)
const PortalCustomWidgetsNameRoute = PortalCustomWidgetsNameRouteImport.update({
  id: '/widgets/$name',
  path: '/widgets/$name',
  getParentRoute: () => PortalCustomRoute,
} as any)
const PortalCustomAlertsIdIndexRoute =
  PortalCustomAlertsIdIndexRouteImport.update({
    id: '/alerts/$id/',
    path: '/alerts/$id/',
    getParentRoute: () => PortalCustomRoute,
  } as any)
const PortalCustomAlertsIdEditRoute =
  PortalCustomAlertsIdEditRouteImport.update({
    id: '/alerts/$id/edit',
    path: '/alerts/$id/edit',
    getParentRoute: () => PortalCustomRoute,
  } as any)
const PortalCustomEditKindNameRoute =
  PortalCustomEditKindNameRouteImport.update({
    id: '/edit/$kind/$name',
    path: '/edit/$kind/$name',
    getParentRoute: () => PortalCustomRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/portal': typeof PortalRouteWithChildren
  '/ic/$person': typeof IcPersonRouteWithChildren
  '/portal/custom': typeof PortalCustomRouteWithChildren
  '/portal/': typeof PortalIndexRoute
  '/ic/$person/personal': typeof IcPersonPersonalRoute
  '/ic/$person/team': typeof IcPersonTeamRoute
  '/portal/custom/$name': typeof PortalCustomNameRoute
  '/ic/$person/': typeof IcPersonIndexRoute
  '/portal/custom/': typeof PortalCustomIndexRoute
  '/portal/custom/alerts/new': typeof PortalCustomAlertsNewRoute
  '/portal/custom/datasets/$name': typeof PortalCustomDatasetsNameRoute
  '/portal/custom/metrics/$name': typeof PortalCustomMetricsNameRoute
  '/portal/custom/new/$kind': typeof PortalCustomNewKindRoute
  '/portal/custom/widgets/$name': typeof PortalCustomWidgetsNameRoute
  '/portal/custom/alerts/': typeof PortalCustomAlertsIndexRoute
  '/portal/custom/datasets/': typeof PortalCustomDatasetsIndexRoute
  '/portal/custom/metrics/': typeof PortalCustomMetricsIndexRoute
  '/portal/custom/widgets/': typeof PortalCustomWidgetsIndexRoute
  '/portal/custom/alerts/$id/edit': typeof PortalCustomAlertsIdEditRoute
  '/portal/custom/edit/$kind/$name': typeof PortalCustomEditKindNameRoute
  '/portal/custom/alerts/$id/': typeof PortalCustomAlertsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/portal': typeof PortalIndexRoute
  '/ic/$person/personal': typeof IcPersonPersonalRoute
  '/ic/$person/team': typeof IcPersonTeamRoute
  '/portal/custom/$name': typeof PortalCustomNameRoute
  '/ic/$person': typeof IcPersonIndexRoute
  '/portal/custom': typeof PortalCustomIndexRoute
  '/portal/custom/alerts/new': typeof PortalCustomAlertsNewRoute
  '/portal/custom/datasets/$name': typeof PortalCustomDatasetsNameRoute
  '/portal/custom/metrics/$name': typeof PortalCustomMetricsNameRoute
  '/portal/custom/new/$kind': typeof PortalCustomNewKindRoute
  '/portal/custom/widgets/$name': typeof PortalCustomWidgetsNameRoute
  '/portal/custom/alerts': typeof PortalCustomAlertsIndexRoute
  '/portal/custom/datasets': typeof PortalCustomDatasetsIndexRoute
  '/portal/custom/metrics': typeof PortalCustomMetricsIndexRoute
  '/portal/custom/widgets': typeof PortalCustomWidgetsIndexRoute
  '/portal/custom/alerts/$id/edit': typeof PortalCustomAlertsIdEditRoute
  '/portal/custom/edit/$kind/$name': typeof PortalCustomEditKindNameRoute
  '/portal/custom/alerts/$id': typeof PortalCustomAlertsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/portal': typeof PortalRouteWithChildren
  '/ic/$person': typeof IcPersonRouteWithChildren
  '/portal/custom': typeof PortalCustomRouteWithChildren
  '/portal/': typeof PortalIndexRoute
  '/ic/$person/personal': typeof IcPersonPersonalRoute
  '/ic/$person/team': typeof IcPersonTeamRoute
  '/portal/custom/$name': typeof PortalCustomNameRoute
  '/ic/$person/': typeof IcPersonIndexRoute
  '/portal/custom/': typeof PortalCustomIndexRoute
  '/portal/custom/alerts/new': typeof PortalCustomAlertsNewRoute
  '/portal/custom/datasets/$name': typeof PortalCustomDatasetsNameRoute
  '/portal/custom/metrics/$name': typeof PortalCustomMetricsNameRoute
  '/portal/custom/new/$kind': typeof PortalCustomNewKindRoute
  '/portal/custom/widgets/$name': typeof PortalCustomWidgetsNameRoute
  '/portal/custom/alerts/': typeof PortalCustomAlertsIndexRoute
  '/portal/custom/datasets/': typeof PortalCustomDatasetsIndexRoute
  '/portal/custom/metrics/': typeof PortalCustomMetricsIndexRoute
  '/portal/custom/widgets/': typeof PortalCustomWidgetsIndexRoute
  '/portal/custom/alerts/$id/edit': typeof PortalCustomAlertsIdEditRoute
  '/portal/custom/edit/$kind/$name': typeof PortalCustomEditKindNameRoute
  '/portal/custom/alerts/$id/': typeof PortalCustomAlertsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/portal'
    | '/ic/$person'
    | '/portal/custom'
    | '/portal/'
    | '/ic/$person/personal'
    | '/ic/$person/team'
    | '/portal/custom/$name'
    | '/ic/$person/'
    | '/portal/custom/'
    | '/portal/custom/alerts/new'
    | '/portal/custom/datasets/$name'
    | '/portal/custom/metrics/$name'
    | '/portal/custom/new/$kind'
    | '/portal/custom/widgets/$name'
    | '/portal/custom/alerts/'
    | '/portal/custom/datasets/'
    | '/portal/custom/metrics/'
    | '/portal/custom/widgets/'
    | '/portal/custom/alerts/$id/edit'
    | '/portal/custom/edit/$kind/$name'
    | '/portal/custom/alerts/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/portal'
    | '/ic/$person/personal'
    | '/ic/$person/team'
    | '/portal/custom/$name'
    | '/ic/$person'
    | '/portal/custom'
    | '/portal/custom/alerts/new'
    | '/portal/custom/datasets/$name'
    | '/portal/custom/metrics/$name'
    | '/portal/custom/new/$kind'
    | '/portal/custom/widgets/$name'
    | '/portal/custom/alerts'
    | '/portal/custom/datasets'
    | '/portal/custom/metrics'
    | '/portal/custom/widgets'
    | '/portal/custom/alerts/$id/edit'
    | '/portal/custom/edit/$kind/$name'
    | '/portal/custom/alerts/$id'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/portal'
    | '/ic/$person'
    | '/portal/custom'
    | '/portal/'
    | '/ic/$person/personal'
    | '/ic/$person/team'
    | '/portal/custom/$name'
    | '/ic/$person/'
    | '/portal/custom/'
    | '/portal/custom/alerts/new'
    | '/portal/custom/datasets/$name'
    | '/portal/custom/metrics/$name'
    | '/portal/custom/new/$kind'
    | '/portal/custom/widgets/$name'
    | '/portal/custom/alerts/'
    | '/portal/custom/datasets/'
    | '/portal/custom/metrics/'
    | '/portal/custom/widgets/'
    | '/portal/custom/alerts/$id/edit'
    | '/portal/custom/edit/$kind/$name'
    | '/portal/custom/alerts/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  PortalRoute: typeof PortalRouteWithChildren
  IcPersonRoute: typeof IcPersonRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ic/$person': {
      id: '/ic/$person'
      path: '/ic/$person'
      fullPath: '/ic/$person'
      preLoaderRoute: typeof IcPersonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/custom': {
      id: '/portal/custom'
      path: '/custom'
      fullPath: '/portal/custom'
      preLoaderRoute: typeof PortalCustomRouteImport
      parentRoute: typeof PortalRoute
    }
    '/ic/$person/': {
      id: '/ic/$person/'
      path: '/'
      fullPath: '/ic/$person/'
      preLoaderRoute: typeof IcPersonIndexRouteImport
      parentRoute: typeof IcPersonRoute
    }
    '/ic/$person/personal': {
      id: '/ic/$person/personal'
      path: '/personal'
      fullPath: '/ic/$person/personal'
      preLoaderRoute: typeof IcPersonPersonalRouteImport
      parentRoute: typeof IcPersonRoute
    }
    '/ic/$person/team': {
      id: '/ic/$person/team'
      path: '/team'
      fullPath: '/ic/$person/team'
      preLoaderRoute: typeof IcPersonTeamRouteImport
      parentRoute: typeof IcPersonRoute
    }
    '/portal/custom/': {
      id: '/portal/custom/'
      path: '/'
      fullPath: '/portal/custom/'
      preLoaderRoute: typeof PortalCustomIndexRouteImport
      parentRoute: typeof PortalCustomRoute
    }
    '/portal/custom/$name': {
      id: '/portal/custom/$name'
      path: '/$name'
      fullPath: '/portal/custom/$name'
      preLoaderRoute: typeof PortalCustomNameRouteImport
      parentRoute: typeof PortalCustomRoute
    }
    '/portal/custom/alerts/': {
      id: '/portal/custom/alerts/'
      path: '/alerts'
      fullPath: '/portal/custom/alerts/'
      preLoaderRoute: typeof PortalCustomAlertsIndexRouteImport
      parentRoute: typeof PortalCustomRoute
    }
    '/portal/custom/alerts/new': {
      id: '/portal/custom/alerts/new'
      path: '/alerts/new'
      fullPath: '/portal/custom/alerts/new'
      preLoaderRoute: typeof PortalCustomAlertsNewRouteImport
      parentRoute: typeof PortalCustomRoute
    }
    '/portal/custom/datasets/': {
      id: '/portal/custom/datasets/'
      path: '/datasets'
      fullPath: '/portal/custom/datasets/'
      preLoaderRoute: typeof PortalCustomDatasetsIndexRouteImport
      parentRoute: typeof PortalCustomRoute
    }
    '/portal/custom/datasets/$name': {
      id: '/portal/custom/datasets/$name'
      path: '/datasets/$name'
      fullPath: '/portal/custom/datasets/$name'
      preLoaderRoute: typeof PortalCustomDatasetsNameRouteImport
      parentRoute: typeof PortalCustomRoute
    }
    '/portal/custom/metrics/': {
      id: '/portal/custom/metrics/'
      path: '/metrics'
      fullPath: '/portal/custom/metrics/'
      preLoaderRoute: typeof PortalCustomMetricsIndexRouteImport
      parentRoute: typeof PortalCustomRoute
    }
    '/portal/custom/metrics/$name': {
      id: '/portal/custom/metrics/$name'
      path: '/metrics/$name'
      fullPath: '/portal/custom/metrics/$name'
      preLoaderRoute: typeof PortalCustomMetricsNameRouteImport
      parentRoute: typeof PortalCustomRoute
    }
    '/portal/custom/new/$kind': {
      id: '/portal/custom/new/$kind'
      path: '/new/$kind'
      fullPath: '/portal/custom/new/$kind'
      preLoaderRoute: typeof PortalCustomNewKindRouteImport
      parentRoute: typeof PortalCustomRoute
    }
    '/portal/custom/widgets/': {
      id: '/portal/custom/widgets/'
      path: '/widgets'
      fullPath: '/portal/custom/widgets/'
      preLoaderRoute: typeof PortalCustomWidgetsIndexRouteImport
      parentRoute: typeof PortalCustomRoute
    }
    '/portal/custom/widgets/$name': {
      id: '/portal/custom/widgets/$name'
      path: '/widgets/$name'
      fullPath: '/portal/custom/widgets/$name'
      preLoaderRoute: typeof PortalCustomWidgetsNameRouteImport
      parentRoute: typeof PortalCustomRoute
    }
    '/portal/custom/alerts/$id/': {
      id: '/portal/custom/alerts/$id/'
      path: '/alerts/$id'
      fullPath: '/portal/custom/alerts/$id/'
      preLoaderRoute: typeof PortalCustomAlertsIdIndexRouteImport
      parentRoute: typeof PortalCustomRoute
    }
    '/portal/custom/alerts/$id/edit': {
      id: '/portal/custom/alerts/$id/edit'
      path: '/alerts/$id/edit'
      fullPath: '/portal/custom/alerts/$id/edit'
      preLoaderRoute: typeof PortalCustomAlertsIdEditRouteImport
      parentRoute: typeof PortalCustomRoute
    }
    '/portal/custom/edit/$kind/$name': {
      id: '/portal/custom/edit/$kind/$name'
      path: '/edit/$kind/$name'
      fullPath: '/portal/custom/edit/$kind/$name'
      preLoaderRoute: typeof PortalCustomEditKindNameRouteImport
      parentRoute: typeof PortalCustomRoute
    }
  }
}

interface PortalCustomRouteChildren {
  PortalCustomNameRoute: typeof PortalCustomNameRoute
  PortalCustomIndexRoute: typeof PortalCustomIndexRoute
  PortalCustomAlertsNewRoute: typeof PortalCustomAlertsNewRoute
  PortalCustomDatasetsNameRoute: typeof PortalCustomDatasetsNameRoute
  PortalCustomMetricsNameRoute: typeof PortalCustomMetricsNameRoute
  PortalCustomNewKindRoute: typeof PortalCustomNewKindRoute
  PortalCustomWidgetsNameRoute: typeof PortalCustomWidgetsNameRoute
  PortalCustomAlertsIndexRoute: typeof PortalCustomAlertsIndexRoute
  PortalCustomDatasetsIndexRoute: typeof PortalCustomDatasetsIndexRoute
  PortalCustomMetricsIndexRoute: typeof PortalCustomMetricsIndexRoute
  PortalCustomWidgetsIndexRoute: typeof PortalCustomWidgetsIndexRoute
  PortalCustomAlertsIdEditRoute: typeof PortalCustomAlertsIdEditRoute
  PortalCustomEditKindNameRoute: typeof PortalCustomEditKindNameRoute
  PortalCustomAlertsIdIndexRoute: typeof PortalCustomAlertsIdIndexRoute
}

const PortalCustomRouteChildren: PortalCustomRouteChildren = {
  PortalCustomNameRoute: PortalCustomNameRoute,
  PortalCustomIndexRoute: PortalCustomIndexRoute,
  PortalCustomAlertsNewRoute: PortalCustomAlertsNewRoute,
  PortalCustomDatasetsNameRoute: PortalCustomDatasetsNameRoute,
  PortalCustomMetricsNameRoute: PortalCustomMetricsNameRoute,
  PortalCustomNewKindRoute: PortalCustomNewKindRoute,
  PortalCustomWidgetsNameRoute: PortalCustomWidgetsNameRoute,
  PortalCustomAlertsIndexRoute: PortalCustomAlertsIndexRoute,
  PortalCustomDatasetsIndexRoute: PortalCustomDatasetsIndexRoute,
  PortalCustomMetricsIndexRoute: PortalCustomMetricsIndexRoute,
  PortalCustomWidgetsIndexRoute: PortalCustomWidgetsIndexRoute,
  PortalCustomAlertsIdEditRoute: PortalCustomAlertsIdEditRoute,
  PortalCustomEditKindNameRoute: PortalCustomEditKindNameRoute,
  PortalCustomAlertsIdIndexRoute: PortalCustomAlertsIdIndexRoute,
}

const PortalCustomRouteWithChildren = PortalCustomRoute._addFileChildren(
  PortalCustomRouteChildren,
)

interface PortalRouteChildren {
  PortalCustomRoute: typeof PortalCustomRouteWithChildren
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalCustomRoute: PortalCustomRouteWithChildren,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

interface IcPersonRouteChildren {
  IcPersonPersonalRoute: typeof IcPersonPersonalRoute
  IcPersonTeamRoute: typeof IcPersonTeamRoute
  IcPersonIndexRoute: typeof IcPersonIndexRoute
}

const IcPersonRouteChildren: IcPersonRouteChildren = {
  IcPersonPersonalRoute: IcPersonPersonalRoute,
  IcPersonTeamRoute: IcPersonTeamRoute,
  IcPersonIndexRoute: IcPersonIndexRoute,
}

const IcPersonRouteWithChildren = IcPersonRoute._addFileChildren(
  IcPersonRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  PortalRoute: PortalRouteWithChildren,
  IcPersonRoute: IcPersonRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
